import { randomUUID } from 'node:crypto';
import type { AccountSummary, DeviceRecord, TaskStatus, UsageEvent } from '@cod/contracts';
import { CHAT_RESPONSE_CACHE_MAX_BYTES, DEVICE_OFFLINE_AFTER_MS, LEGACY_TASK_INTERRUPTED_ERROR, TASK_LEASE_DURATION_MS, TASK_LEASE_EXPIRED_ERROR, USAGE_RESERVATION_LEASE_DURATION_MS, USAGE_RESERVATION_REAP_BATCH_SIZE, USAGE_RESERVATION_REAP_INTERVAL_MS, creditPackCatalog, hashTaskLeaseToken, validateDeviceInput, validateTaskExecutionClaimCredential, validateTaskExecutionCredential, validateTaskOutcome, validateTaskTransition, type AuditEntry, type ChatRequestClaim, type ChatRequestCompletion, type CodDatabase, type CreditGrant, type CreditSummary, type IdentityRecord, type LedgerEntry, type PaymentCompletion, type PaymentOrder, type PaymentOrderRequest, type Principal, type SyncedTask, type TaskEvent, type TaskExecutionClaim, type TaskExecutionClaimCredential, type TaskExecutionCredential, type TaskLeaseHeartbeat, type TaskOutcome, type TopupRequest } from './database.js';
import { HttpError } from './errors.js';
import type { ComputeRequest, ComputeRequestInput } from './compute-market.js';
import { recordUsageReservationsReaped } from './metrics.js';

interface UserState {
  account: AccountSummary;
  ledger: LedgerEntry[];
  idempotency: Map<string, LedgerEntry>;
  devices: Map<string, DeviceRecord>;
  tasks: Map<string, SyncedTask>;
  events: TaskEvent[];
  audit: AuditEntry[];
  reservations: Map<string, { amountCents: number; walletCents: number; grantAllocations: Array<{grantId:string;amountCents:number}>; taskId: string | null; executionId: string | null; status: 'reserved' | 'settled' | 'released'; leaseExpiresAt: number }>;
  chatRequests: Map<string, { fingerprint: string; executionId: string | null; status: 'pending' | 'complete' | 'failed'; responsePayload: Record<string,unknown> | null; expiresAt: number }>;
  taskExecutions: Map<string, { executionId: string; claimIdHash: string; leaseTokenHash: string; leaseExpiresAt: number }>;
  creditGrants: Map<string,CreditGrant>;
  creditPackIdempotency: Map<string,string>;
  paymentOrders: Map<string, PaymentOrder>;
  paymentIdempotency: Map<string, string>;
  computeRequests: Map<string, ComputeRequest>;
  computeIdempotency: Map<string, string>;
}

export class MemoryDatabase implements CodDatabase {
  private readonly users = new Map<string, UserState>();
  private readonly identities = new Map<string, IdentityRecord>();
  private readonly providerEvents = new Map<string, string>();
  private reservationReaperTimer:NodeJS.Timeout|null=null;
  private reservationReaperRun:Promise<number>|null=null;
  async initialize() { await this.reapExpiredUsageReservations();if(!this.reservationReaperTimer){this.reservationReaperTimer=setInterval(()=>{if(this.reservationReaperRun)return;const run=this.reapExpiredUsageReservations();this.reservationReaperRun=run;void run.catch((error:unknown)=>console.error(JSON.stringify({level:'error',event:'usage.reservations.reap_failed',error:error instanceof Error?error.message:String(error)}))).finally(()=>{if(this.reservationReaperRun===run)this.reservationReaperRun=null;});},USAGE_RESERVATION_REAP_INTERVAL_MS);this.reservationReaperTimer.unref();} }
  async close() { if(this.reservationReaperTimer){clearInterval(this.reservationReaperTimer);this.reservationReaperTimer=null;}if(this.reservationReaperRun)await this.reservationReaperRun.catch(()=>undefined); }
  async health() { return true; }
  async ensurePrincipal(p: Principal) { this.state(p);this.ensureLegacyIdentity(p); }
  async findIdentityByEmail(email:string){return this.identities.get(email.toLowerCase())??null;}
  async registerIdentity(p:Principal,passwordHash:string,inviteCode:string|null,allowExisting:boolean){
    const email=p.email.toLowerCase();const current=this.identities.get(email);
    if(current?.passwordHash)throw new HttpError('该邮箱已经注册，请直接登录',409,'email_registered');
    if(current&&!allowExisting)throw new HttpError('这是旧试点账号，请使用旧访问码完成一次性迁移',409,'legacy_migration_required');
    let inviter:IdentityRecord|null=null;
    if(inviteCode){inviter=[...this.identities.values()].find((identity)=>identity.inviteCode?.toUpperCase()===inviteCode.toUpperCase())??null;if(!inviter)throw new HttpError('邀请码无效',400,'invalid_invite_code');}
    const identity:IdentityRecord={principal:current?.principal??p,passwordHash,inviteCode:current?.inviteCode??`KAI-${p.userId.replace(/^usr_/,'').slice(0,10).toUpperCase()}`,referredByUserId:current?.referredByUserId??inviter?.principal.userId??null,referralCodeUsed:current?.referralCodeUsed??inviter?.inviteCode??null};
    this.state(identity.principal);this.identities.set(email,identity);return{identity,created:!current};
  }
  async getReferralSummary(p:Principal){const identity=this.identities.get(p.email.toLowerCase());if(!identity?.inviteCode)throw new HttpError('Referral profile not found',404,'referral_profile_not_found');return{inviteCode:identity.inviteCode,referredUsers:[...this.identities.values()].filter((item)=>item.referredByUserId===p.userId).length,commissionRateBps:0,pendingCommissionCents:0,settledCommissionCents:0};}
  async getAccount(p: Principal) { return { ...this.state(p).account }; }
  async getLedger(p: Principal) { return [...this.state(p).ledger]; }
  async getCreditSummary(p:Principal):Promise<CreditSummary>{const state=this.state(p);this.expireGrants(state);const grants=[...state.creditGrants.values()].sort((a,b)=>a.expiresAt.localeCompare(b.expiresAt));return{availableCents:grants.filter((grant)=>grant.status==='active').reduce((total,grant)=>total+grant.remainingCents,0),grants:grants.map((grant)=>({...grant}))};}
  async purchaseCreditPack(p:Principal,packId:string,idempotencyKey:string){const state=this.state(p);const pack=creditPackCatalog.find((item)=>item.id===packId);if(!pack)throw new HttpError('Credit pack not found',404,'credit_pack_not_found');if(!idempotencyKey||idempotencyKey.length>200)throw new HttpError('Credit pack idempotency key is invalid',400,'invalid_idempotency_key');const existingId=state.creditPackIdempotency.get(idempotencyKey);if(existingId){const existing=state.creditGrants.get(existingId)!;if(existing.packId!==pack.id)throw new HttpError('Idempotency key was already used with another credit pack',409,'idempotency_conflict');return{grant:{...existing},account:{...state.account},summary:await this.getCreditSummary(p)};}if(state.account.balanceCents<pack.priceCents)throw new HttpError('Insufficient wallet balance',402,'insufficient_balance');const purchasedAt=new Date();const grant:CreditGrant={id:randomUUID(),packId:pack.id,name:pack.name,originalCents:pack.creditCents,remainingCents:pack.creditCents,purchasedAt:purchasedAt.toISOString(),expiresAt:new Date(purchasedAt.getTime()+180*24*60*60*1000).toISOString(),status:'active'};state.account={...state.account,balanceCents:state.account.balanceCents-pack.priceCents};state.creditGrants.set(grant.id,grant);state.creditPackIdempotency.set(idempotencyKey,grant.id);const purchase:LedgerEntry={id:randomUUID(),type:'pack_purchase',amountCents:-pack.priceCents,walletAmountCents:-pack.priceCents,creditAmountCents:0,createdAt:new Date().toISOString(),reference:pack.name,sourceId:null,model:null,paymentDirection:'COD 钱包 → 180 天额度包'};const credit:LedgerEntry={id:randomUUID(),type:'credit_grant',amountCents:pack.creditCents,walletAmountCents:0,creditAmountCents:pack.creditCents,createdAt:new Date().toISOString(),reference:pack.name,sourceId:null,model:null,paymentDirection:'额度包 → COD 使用额度'};state.ledger.unshift(credit,purchase);return{grant:{...grant},account:{...state.account},summary:await this.getCreditSummary(p)};}
  async topup(p: Principal, request: TopupRequest) {
    const state=this.state(p); const existing=state.idempotency.get(request.idempotencyKey); if(existing) return existing;
    if(!Number.isInteger(request.amountCents)||request.amountCents<100||request.amountCents>1_000_000) throw new HttpError('Top-up amount must be between 100 and 1000000 cents',400,'invalid_topup');
    const entry:LedgerEntry={id:randomUUID(),type:'topup',amountCents:request.amountCents,walletAmountCents:request.amountCents,creditAmountCents:0,createdAt:new Date().toISOString(),reference:`${request.channel}:${request.idempotencyKey}`,sourceId:null,model:null,paymentDirection:'用户 → COD 钱包'};
    state.account={...state.account,balanceCents:state.account.balanceCents+request.amountCents}; state.ledger.unshift(entry); state.idempotency.set(request.idempotencyKey,entry); return entry;
  }
  async createPaymentOrder(p: Principal, request: PaymentOrderRequest) {
    const state=this.state(p);
    if(!Number.isInteger(request.amountCents)||request.amountCents<100||request.amountCents>1_000_000)throw new HttpError('Payment amount must be between 100 and 1000000 cents',400,'invalid_payment_amount');
    if(request.channel!=='wechat'&&request.channel!=='alipay')throw new HttpError('Payment channel is invalid',400,'invalid_payment_channel');
    const existingId=state.paymentIdempotency.get(request.idempotencyKey);const existing=existingId?state.paymentOrders.get(existingId):null;
    if(existing){if(existing.amountCents!==request.amountCents||existing.channel!==request.channel)throw new HttpError('Idempotency key was already used with different payment parameters',409,'idempotency_conflict');return existing;}
    const now=new Date().toISOString();const order:PaymentOrder={id:randomUUID(),amountCents:request.amountCents,currency:'CNY',channel:request.channel,status:'pending',providerPaymentId:null,createdAt:now,updatedAt:now};state.paymentOrders.set(order.id,order);state.paymentIdempotency.set(request.idempotencyKey,order.id);return order;
  }
  async getPaymentOrder(p:Principal,orderId:string){const order=this.state(p).paymentOrders.get(orderId);if(!order)throw new HttpError('Payment order not found',404,'payment_order_not_found');return order;}
  async completePaymentOrder(event:PaymentCompletion){
    const eventOrder=this.providerEvents.get(event.providerEventId);if(eventOrder&&eventOrder!==event.orderId)throw new HttpError('Provider payment or event was already used for another order',409,'payment_provider_reused');
    for(const state of this.users.values())for(const order of state.paymentOrders.values())if(order.id!==event.orderId&&order.providerPaymentId===event.providerPaymentId)throw new HttpError('Provider payment or event was already used for another order',409,'payment_provider_reused');
    for(const state of this.users.values()){
      const current=state.paymentOrders.get(event.orderId);if(!current)continue;
      if(current.amountCents!==event.amountCents||current.currency!==event.currency||current.channel!==event.channel)throw new HttpError('Payment event does not match the order',409,'payment_order_mismatch');
      const ledgerKey=`payment-order:${current.id}`;const existing=state.idempotency.get(ledgerKey);
      if(current.status==='paid'){if(current.providerPaymentId!==event.providerPaymentId)throw new HttpError('Payment order is already bound to another provider payment',409,'payment_provider_conflict');if(!existing)throw new HttpError('Paid order ledger entry is missing',500,'payment_ledger_missing');return{order:current,entry:existing};}
      if(current.status!=='pending')throw new HttpError(`Payment order cannot be completed from ${current.status}`,409,'payment_order_not_pending');
      const entry:LedgerEntry={id:randomUUID(),type:'topup',amountCents:current.amountCents,walletAmountCents:current.amountCents,creditAmountCents:0,createdAt:new Date().toISOString(),reference:`${event.channel}:${event.providerPaymentId}`,sourceId:null,model:null,paymentDirection:'用户 → 支付渠道 → COD 钱包'};
      const order:PaymentOrder={...current,status:'paid',providerPaymentId:event.providerPaymentId,updatedAt:new Date().toISOString()};state.account={...state.account,balanceCents:state.account.balanceCents+current.amountCents};state.ledger.unshift(entry);state.idempotency.set(ledgerKey,entry);state.paymentOrders.set(order.id,order);this.providerEvents.set(event.providerEventId,order.id);return{order,entry};
    }
    throw new HttpError('Payment order not found',404,'payment_order_not_found');
  }
  async recordUsage(p: Principal,event:UsageEvent) {
    const state=this.state(p); const existing=state.idempotency.get(event.idempotencyKey); if(existing) return existing;
    if(!Number.isInteger(event.costCents)||event.costCents<0) throw new HttpError('Usage cost is invalid',400,'invalid_usage');
    const billedEvent=p.role==='admin'?{...event,costCents:0,paymentDirection:'管理员测试免计费',commissionRateBps:0,commissionCents:0}:event;const allocation=this.allocateFunds(state,billedEvent.costCents);const creditCents=allocation.grantAllocations.reduce((total,item)=>total+item.amountCents,0);
    const entry=this.usageEntry(billedEvent,allocation.walletCents,creditCents);state.ledger.unshift(entry); state.idempotency.set(event.idempotencyKey,entry); return entry;
  }
  async claimChatRequest(p:Principal,requestKey:string,fingerprint:string,executionId?:string):Promise<ChatRequestClaim>{
    if(!requestKey||requestKey.length>240)throw new HttpError('Chat request key is invalid',400,'invalid_idempotency_key');
    if(!/^[a-f0-9]{64}$/.test(fingerprint))throw new HttpError('Chat request fingerprint is invalid',400,'invalid_request_fingerprint');
    const state=this.state(p);const now=Date.now();let removed=0;for(const user of this.users.values()){for(const [key,item] of user.chatRequests){if(item.expiresAt<=now){user.chatRequests.delete(key);removed+=1;if(removed>=1000)break;}}if(removed>=1000)break;}const existing=state.chatRequests.get(requestKey);
    if(executionId&&!/^[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}$/i.test(executionId))throw new HttpError('Task execution is invalid',400,'invalid_task_execution');
    if(!existing){state.chatRequests.set(requestKey,{fingerprint,executionId:executionId??null,status:'pending',responsePayload:null,expiresAt:now+60*60*1000});return{state:'claimed'};}
    if(existing.fingerprint!==fingerprint)throw new HttpError('Request ID was already used for a different chat request',409,'idempotency_conflict');
    if(existing.executionId!==(executionId??null))throw new HttpError('Request ID belongs to another task execution',409,'idempotency_conflict');
    if(existing.status==='complete'){
      if(!existing.responsePayload)throw new HttpError('Cached chat response is invalid',500,'chat_cache_invalid');
      return{state:'complete',responsePayload:structuredClone(existing.responsePayload)};
    }
    if(existing.status==='pending')return{state:'pending'};
    state.chatRequests.set(requestKey,{fingerprint,executionId:executionId??null,status:'pending',responsePayload:null,expiresAt:now+60*60*1000});return{state:'claimed'};
  }
  async failChatRequest(p:Principal,requestKey:string,fingerprint:string,executionId?:string){
    const state=this.state(p);const existing=state.chatRequests.get(requestKey);if(!existing||existing.fingerprint!==fingerprint||existing.executionId!==(executionId??null)||existing.status!=='pending')return;
    if(state.idempotency.has(`chat:${requestKey}:${fingerprint}`))return;
    state.chatRequests.set(requestKey,{...existing,status:'failed',responsePayload:null,expiresAt:Date.now()+60*60*1000});
  }
  async reserveUsage(p:Principal,id:string,amountCents:number,taskExecution?:{taskId:string;executionId:string}){
    if(!Number.isInteger(amountCents)||amountCents<0)throw new HttpError('Reservation amount is invalid',400,'invalid_reservation');
    await this.reapExpiredUsageReservations();
    const state=this.state(p);const existing=state.reservations.get(id);
    if(existing){if(existing.taskId!==(taskExecution?.taskId??null)||existing.executionId!==(taskExecution?.executionId??null))throw new HttpError('Reservation belongs to another task execution',409,'reservation_execution_conflict');if(existing.status!=='reserved'||existing.leaseExpiresAt<=Date.now())throw new HttpError('Usage reservation lease is no longer active',409,'reservation_lease_expired');return;}
    if(taskExecution)this.assertExecutionState(state,taskExecution.taskId,taskExecution.executionId);
    const reservableAmount=p.role==='admin'?0:amountCents;const allocation=this.allocateFunds(state,reservableAmount);
    state.reservations.set(id,{amountCents:reservableAmount,...allocation,taskId:taskExecution?.taskId??null,executionId:taskExecution?.executionId??null,status:'reserved',leaseExpiresAt:Date.now()+USAGE_RESERVATION_LEASE_DURATION_MS});
  }
  async renewUsageReservation(p:Principal,id:string){const reservation=this.state(p).reservations.get(id);if(!reservation||reservation.status!=='reserved'||reservation.leaseExpiresAt<=Date.now())throw new HttpError('Usage reservation lease is no longer active',409,'reservation_lease_expired');reservation.leaseExpiresAt=Date.now()+USAGE_RESERVATION_LEASE_DURATION_MS;}
  async reapExpiredUsageReservations(limit:number=USAGE_RESERVATION_REAP_BATCH_SIZE){
    const boundedLimit=Math.min(Math.max(Number.isFinite(limit)?Math.trunc(limit):USAGE_RESERVATION_REAP_BATCH_SIZE,1),USAGE_RESERVATION_REAP_BATCH_SIZE);let released=0;
    const candidates=[...this.users.values()].flatMap((state)=>[...state.reservations.values()].map((reservation)=>({state,reservation}))).filter(({reservation})=>reservation.status==='reserved'&&reservation.leaseExpiresAt<=Date.now()).sort((a,b)=>a.reservation.leaseExpiresAt-b.reservation.leaseExpiresAt).slice(0,boundedLimit);
    for(const {state,reservation} of candidates){if(reservation.status!=='reserved'||reservation.leaseExpiresAt>Date.now())continue;this.releaseReservation(state,reservation);released+=1;}
    if(released>0)recordUsageReservationsReaped(released);return released;
  }
  async settleUsage(p:Principal,id:string,event:UsageEvent,completion?:ChatRequestCompletion,executionId?:string){
    const state=this.state(p);const reservation=state.reservations.get(id);const chatRequest=completion?state.chatRequests.get(completion.requestKey):null;const cachedResponse=completion?structuredClone(completion.responsePayload):null;const auditData=completion?structuredClone(completion.audit.data):null;
    if(completion){if(event.idempotencyKey!==`chat:${completion.requestKey}:${completion.fingerprint}`)throw new HttpError('Chat settlement key is invalid',400,'invalid_idempotency_key');if(Buffer.byteLength(JSON.stringify(completion.responsePayload),'utf8')>CHAT_RESPONSE_CACHE_MAX_BYTES)throw new HttpError('Model response is too large to cache safely',502,'chat_response_cache_too_large');if(!chatRequest||chatRequest.fingerprint!==completion.fingerprint||chatRequest.executionId!==(completion.executionId??null))throw new HttpError('Chat request claim was not found',409,'chat_request_not_claimed');if(chatRequest.status==='failed')throw new HttpError('Chat request is no longer pending',409,'chat_request_not_pending');}
    if(event.taskId!=='chat'&&(!executionId||reservation?.taskId!==event.taskId||reservation.executionId!==executionId))throw new HttpError('Reservation belongs to another task execution',409,'reservation_execution_conflict');
    const existing=state.idempotency.get(event.idempotencyKey);if(existing){if(reservation?.status==='reserved')this.releaseReservation(state,reservation);if(completion&&chatRequest?.status==='pending')state.chatRequests.set(completion.requestKey,{fingerprint:completion.fingerprint,executionId:completion.executionId??null,status:'complete',responsePayload:cachedResponse!,expiresAt:Date.now()+24*60*60*1000});return existing;}
    if(event.taskId!=='chat')this.assertExecutionState(state,event.taskId,executionId!);
    if(completion&&chatRequest?.status==='complete')throw new HttpError('Completed chat request is missing its billing record',500,'chat_billing_inconsistent');if(!reservation||reservation.status!=='reserved'||reservation.leaseExpiresAt<=Date.now())throw new HttpError('Usage reservation lease is no longer active',409,'reservation_lease_expired');
    const billedEvent=p.role==='admin'?{...event,costCents:0,paymentDirection:'管理员测试免计费',commissionRateBps:0,commissionCents:0}:event;let remaining=billedEvent.costCents;let creditConsumed=0;for(const allocation of reservation.grantAllocations){const consumed=Math.min(allocation.amountCents,remaining);creditConsumed+=consumed;remaining-=consumed;this.restoreGrant(state,allocation.grantId,allocation.amountCents-consumed);}const walletConsumed=Math.min(reservation.walletCents,remaining);remaining-=walletConsumed;state.account={...state.account,balanceCents:state.account.balanceCents+reservation.walletCents-walletConsumed};let totalWallet=walletConsumed;if(remaining>0){const extra=this.allocateFunds(state,remaining);totalWallet+=extra.walletCents;creditConsumed+=extra.grantAllocations.reduce((total,item)=>total+item.amountCents,0);}const entry=this.usageEntry(billedEvent,totalWallet,creditConsumed);state.ledger.unshift(entry);state.idempotency.set(event.idempotencyKey,entry);reservation.status='settled';
    if(completion){state.chatRequests.set(completion.requestKey,{fingerprint:completion.fingerprint,executionId:completion.executionId??null,status:'complete',responsePayload:cachedResponse!,expiresAt:Date.now()+24*60*60*1000});state.audit.unshift({id:randomUUID(),action:'chat.complete',entityType:'model',entityId:completion.audit.entityId,data:auditData,createdAt:new Date().toISOString()});}return entry;
  }
  async releaseUsage(p:Principal,id:string){const state=this.state(p);const reservation=state.reservations.get(id);if(!reservation||reservation.status!=='reserved')return;this.releaseReservation(state,reservation);}
  async createComputeRequest(p:Principal,input:ComputeRequestInput,idempotencyKey:string){const state=this.state(p);if(!idempotencyKey||idempotencyKey.length>200)throw new HttpError('Compute request idempotency key is invalid',400,'invalid_idempotency_key');const existingId=state.computeIdempotency.get(idempotencyKey);if(existingId)return{...state.computeRequests.get(existingId)!};const now=new Date().toISOString();const request:ComputeRequest={...input,id:randomUUID(),email:p.email,offerId:input.offerId??null,durationHours:input.durationHours??null,termMonths:input.termMonths??null,status:'submitted',createdAt:now,updatedAt:now};state.computeRequests.set(request.id,request);state.computeIdempotency.set(idempotencyKey,request.id);return{...request};}
  async listComputeRequests(p:Principal){return[...this.state(p).computeRequests.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map((request)=>({...request}));}
  async listDevices(p:Principal){const state=this.state(p);return[...state.devices.values()].map((device)=>{if(Date.now()-new Date(device.lastSeenAt).getTime()<=DEVICE_OFFLINE_AFTER_MS)return device;const offline={...device,status:'offline' as const};state.devices.set(device.id,offline);return offline;});}
  async registerDevice(p:Principal,input:Pick<DeviceRecord,'name'|'platform'>){validateDeviceInput(input);const state=this.state(p);const device:DeviceRecord={id:randomUUID(),name:input.name.trim().slice(0,100),platform:input.platform,status:'online',lastSeenAt:new Date().toISOString()};state.devices.set(device.id,device);this.append(state,'device.registered',device.id,device);return device;}
  async heartbeat(p:Principal,id:string,taskLease?:TaskLeaseHeartbeat){const state=this.state(p);const current=state.devices.get(id);if(!current)throw new HttpError('Device not found',404,'device_not_found');if(taskLease){validateTaskExecutionCredential(taskLease);const execution=state.taskExecutions.get(taskLease.taskId);const task=state.tasks.get(taskLease.taskId);if(!execution||!task||task.deviceId!==id||!['running','waiting'].includes(task.status)||execution.executionId!==taskLease.executionId||execution.leaseTokenHash!==hashTaskLeaseToken(taskLease.leaseToken)||execution.leaseExpiresAt<=Date.now())throw new HttpError('Task execution lease is no longer active',409,'task_lease_expired');state.taskExecutions.set(taskLease.taskId,{...execution,leaseExpiresAt:Date.now()+TASK_LEASE_DURATION_MS});}const device={...current,status:'online' as const,lastSeenAt:new Date().toISOString()};state.devices.set(id,device);return device;}
  async listTasks(p:Principal){const state=this.state(p);this.expireTaskLeases(state);return[...state.tasks.values()];}
  async getTask(p:Principal,id:string){const state=this.state(p);this.expireTaskLeases(state,id);const task=state.tasks.get(id);if(!task)throw new HttpError('Task not found',404,'task_not_found');return task;}
  async createTask(p:Principal,input:Pick<SyncedTask,'title'|'deviceId'>){const state=this.state(p);if(!input.title?.trim())throw new HttpError('Task title is required',400,'invalid_task');const device=state.devices.get(input.deviceId);if(!device)throw new HttpError('Device not found',404,'device_not_found');if(device.status!=='online'||Date.now()-new Date(device.lastSeenAt).getTime()>DEVICE_OFFLINE_AFTER_MS)throw new HttpError('Device is offline',409,'device_offline');const task:SyncedTask={id:randomUUID(),title:input.title.trim().slice(0,500),deviceId:input.deviceId,status:'draft',updatedAt:new Date().toISOString(),version:1,result:null,error:null};state.tasks.set(task.id,task);this.append(state,'task.created',task.id,task);return task;}
  async claimTask(p:Principal,id:string,version:number,claim:TaskExecutionClaimCredential):Promise<TaskExecutionClaim>{const state=this.state(p);validateTaskExecutionClaimCredential(claim);this.expireTaskLeases(state,id);const current=state.tasks.get(id);if(!current)throw new HttpError('Task not found',404,'task_not_found');const active=state.taskExecutions.get(id);if(current.status==='running'||current.status==='waiting'){if(!active||active.claimIdHash!==hashTaskLeaseToken(claim.claimId)||active.leaseTokenHash!==hashTaskLeaseToken(claim.leaseToken)||active.leaseExpiresAt<=Date.now())throw new HttpError('Task already has an active execution',409,'task_already_running');return{task:current,executionId:active.executionId,leaseToken:claim.leaseToken,leaseExpiresAt:new Date(active.leaseExpiresAt).toISOString(),replayed:true};}if(current.version!==version)throw new HttpError('Task version conflict',409,'version_conflict');validateTaskTransition(current.status,'running');const device=state.devices.get(current.deviceId);if(!device||device.status!=='online'||Date.now()-new Date(device.lastSeenAt).getTime()>DEVICE_OFFLINE_AFTER_MS)throw new HttpError('Device is offline',409,'device_offline');const executionId=randomUUID();const leaseExpiresAt=Date.now()+TASK_LEASE_DURATION_MS;const task={...current,status:'running' as const,result:null,error:null,version:current.version+1,updatedAt:new Date().toISOString()};state.tasks.set(id,task);state.taskExecutions.set(id,{executionId,claimIdHash:hashTaskLeaseToken(claim.claimId),leaseTokenHash:hashTaskLeaseToken(claim.leaseToken),leaseExpiresAt});this.append(state,'task.updated',id,task);state.audit.unshift({id:randomUUID(),action:'task.execution.claim',entityType:'task',entityId:id,data:{executionId,leaseExpiresAt:new Date(leaseExpiresAt).toISOString()},createdAt:new Date().toISOString()});return{task,executionId,leaseToken:claim.leaseToken,leaseExpiresAt:new Date(leaseExpiresAt).toISOString(),replayed:false};}
  async assertTaskExecution(p:Principal,id:string,executionId:string){const state=this.state(p);this.expireTaskLeases(state,id);return this.assertExecutionState(state,id,executionId);}
  async assertTaskLease(p:Principal,id:string,execution:TaskExecutionCredential){validateTaskExecutionCredential(execution);const state=this.state(p);this.expireTaskLeases(state,id);const task=this.assertExecutionState(state,id,execution.executionId);const active=state.taskExecutions.get(id)!;if(active.leaseTokenHash!==hashTaskLeaseToken(execution.leaseToken))throw new HttpError('Task execution lease is no longer active',409,'task_lease_expired');return task;}
  async renewTaskExecution(p:Principal,id:string,executionId:string){const state=this.state(p);this.assertExecutionState(state,id,executionId);const active=state.taskExecutions.get(id)!;state.taskExecutions.set(id,{...active,leaseExpiresAt:Date.now()+TASK_LEASE_DURATION_MS});}
  async updateTask(p:Principal,id:string,status:TaskStatus,version:number,outcome:TaskOutcome={},execution?:TaskExecutionCredential){const state=this.state(p);this.expireTaskLeases(state,id);const current=state.tasks.get(id);if(!current)throw new HttpError('Task not found',404,'task_not_found');if(current.version!==version)throw new HttpError('Task version conflict',409,'version_conflict');if(status==='running'&&current.status!=='running'&&current.status!=='waiting')throw new HttpError('Running tasks must claim a new execution lease',409,'task_claim_required');validateTaskTransition(current.status,status);if((current.status==='running'||current.status==='waiting')&&status!=='cancelled'){if(!execution)throw new HttpError('Task execution lease is required',409,'task_lease_required');validateTaskExecutionCredential(execution);const active=state.taskExecutions.get(id);if(!active||active.executionId!==execution.executionId||active.leaseTokenHash!==hashTaskLeaseToken(execution.leaseToken)||active.leaseExpiresAt<=Date.now())throw new HttpError('Task execution lease is no longer active',409,'task_lease_expired');}if(outcome.result!==undefined&&outcome.result!==null&&outcome.result.length>50_000)throw new HttpError('Task result is too large',400,'task_result_too_large');if(outcome.error!==undefined&&outcome.error!==null&&outcome.error.length>5_000)throw new HttpError('Task error is too large',400,'task_error_too_large');if(current.status===status&&outcome.result===undefined&&outcome.error===undefined)return current;let result=outcome.result===undefined?current.result:outcome.result;let error=outcome.error===undefined?current.error:outcome.error;if(current.status==='waiting'&&status==='running'){result=null;error=null;}if(status==='complete')error=null;if(status==='failed')result=null;if(status==='cancelled'){result=null;error=null;}validateTaskOutcome(status,result,error);const task={...current,status,result,error,version:current.version+1,updatedAt:new Date().toISOString()};state.tasks.set(id,task);if(status==='complete'||status==='failed'||status==='cancelled')state.taskExecutions.delete(id);this.append(state,'task.updated',id,task);return task;}
  async eventsAfter(p:Principal,cursor:number){return this.state(p).events.filter((event)=>event.cursor>cursor);}
  async audit(p:Principal,action:string,entityType:string,entityId:string|null,data:unknown={}){this.state(p).audit.unshift({id:randomUUID(),action,entityType,entityId,data,createdAt:new Date().toISOString()});}
  async listAudit(p:Principal,limit:number){return this.state(p).audit.slice(0,Math.min(Math.max(limit,1),200));}
  private key(p:Principal){return `${p.tenantId}:${p.userId}`;}
  private ensureLegacyIdentity(p:Principal){const email=p.email.toLowerCase();if(!this.identities.has(email))this.identities.set(email,{principal:p,passwordHash:null,inviteCode:`KAI-${p.userId.replace(/^usr_/,'').slice(0,10).toUpperCase()}`,referredByUserId:null,referralCodeUsed:null});}
  private state(p:Principal){const key=this.key(p);let state=this.users.get(key);if(!state){const now=new Date();const trial:CreditGrant={id:randomUUID(),packId:'trial',name:'新用户试用金',originalCents:1000,remainingCents:1000,purchasedAt:now.toISOString(),expiresAt:new Date(now.getTime()+30*24*60*60*1000).toISOString(),status:'active'};const trialEntry:LedgerEntry={id:randomUUID(),type:'trial_credit',amountCents:1000,walletAmountCents:0,creditAmountCents:1000,createdAt:now.toISOString(),reference:'新用户试用金',sourceId:null,model:null,paymentDirection:'平台赠送 → COD 使用额度'};state={account:{userId:p.userId,displayName:p.email.split('@')[0],balanceCents:0,currency:'CNY',plan:p.role==='admin'?'team':'developer',role:p.role,billingExempt:p.role==='admin'},ledger:[trialEntry],idempotency:new Map(),devices:new Map(),tasks:new Map(),taskExecutions:new Map(),events:[],audit:[],reservations:new Map(),chatRequests:new Map(),creditGrants:new Map([[trial.id,trial]]),creditPackIdempotency:new Map(),paymentOrders:new Map(),paymentIdempotency:new Map(),computeRequests:new Map(),computeIdempotency:new Map()};this.users.set(key,state);}return state;}
  private expireTaskLeases(state:UserState,taskId?:string){for(const [id,current]of state.tasks){if(taskId&&id!==taskId)continue;if(current.status!=='running'&&current.status!=='waiting')continue;const execution=state.taskExecutions.get(id);if(execution&&execution.leaseExpiresAt>Date.now())continue;const legacy=!execution;const task={...current,status:'failed' as const,result:null,error:legacy?LEGACY_TASK_INTERRUPTED_ERROR:TASK_LEASE_EXPIRED_ERROR,version:current.version+1,updatedAt:new Date().toISOString()};state.tasks.set(id,task);state.taskExecutions.delete(id);this.append(state,'task.updated',id,task);state.audit.unshift({id:randomUUID(),action:'task.execution.interrupted',entityType:'task',entityId:id,data:{reason:legacy?'legacy_missing_lease':'lease_expired',executionId:execution?.executionId??null},createdAt:new Date().toISOString()});}}
  private assertExecutionState(state:UserState,taskId:string,executionId:string):SyncedTask{const task=state.tasks.get(taskId);const execution=state.taskExecutions.get(taskId);if(!task)throw new HttpError('Task not found',404,'task_not_found');if(!execution||execution.executionId!==executionId||execution.leaseExpiresAt<=Date.now()||(task.status!=='running'&&task.status!=='waiting'))throw new HttpError('Task execution lease is no longer active',409,'task_lease_expired');return task;}
  private expireGrants(state:UserState){for(const [id,grant] of state.creditGrants)if(grant.status==='active'&&new Date(grant.expiresAt).getTime()<=Date.now())state.creditGrants.set(id,{...grant,status:'expired'});}
  private allocateFunds(state:UserState,amountCents:number){this.expireGrants(state);let remaining=amountCents;const grantAllocations:Array<{grantId:string;amountCents:number}>=[];const active=[...state.creditGrants.values()].filter((grant)=>grant.status==='active'&&grant.remainingCents>0).sort((a,b)=>a.expiresAt.localeCompare(b.expiresAt));for(const grant of active){if(remaining<=0)break;const amount=Math.min(grant.remainingCents,remaining);grantAllocations.push({grantId:grant.id,amountCents:amount});remaining-=amount;state.creditGrants.set(grant.id,{...grant,remainingCents:grant.remainingCents-amount,status:grant.remainingCents===amount?'depleted':'active'});}if(state.account.balanceCents<remaining){for(const allocation of grantAllocations)this.restoreGrant(state,allocation.grantId,allocation.amountCents);throw new HttpError('Insufficient balance',402,'insufficient_balance');}state.account={...state.account,balanceCents:state.account.balanceCents-remaining};return{walletCents:remaining,grantAllocations};}
  private restoreGrant(state:UserState,grantId:string,amountCents:number){if(amountCents<=0)return;const grant=state.creditGrants.get(grantId);if(!grant)return;const remainingCents=Math.min(grant.originalCents,grant.remainingCents+amountCents);state.creditGrants.set(grantId,{...grant,remainingCents,status:new Date(grant.expiresAt).getTime()<=Date.now()?'expired':'active'});}
  private releaseReservation(state:UserState,reservation:{walletCents:number;grantAllocations:Array<{grantId:string;amountCents:number}>;status:'reserved'|'settled'|'released'}){state.account={...state.account,balanceCents:state.account.balanceCents+reservation.walletCents};for(const allocation of reservation.grantAllocations)this.restoreGrant(state,allocation.grantId,allocation.amountCents);reservation.status='released';}
  private usageEntry(event:UsageEvent,walletCents:number,creditCents:number):LedgerEntry{return{id:randomUUID(),type:'usage',amountCents:event.costCents?-event.costCents:0,walletAmountCents:walletCents?-walletCents:0,creditAmountCents:creditCents?-creditCents:0,createdAt:new Date().toISOString(),reference:`${event.sourceId}:${event.model}:${event.taskId}`,sourceId:event.sourceId,upstreamSourceId:event.upstreamSourceId??'ai-kai',model:event.model,paymentDirection:event.paymentDirection,commissionRateBps:event.commissionRateBps??0,commissionCents:event.commissionCents??0};}
  private append(state:UserState,type:TaskEvent['type'],entityId:string,data:unknown){state.events.push({cursor:state.events.length+1,type,entityId,data,createdAt:new Date().toISOString()});}
}
