import { randomUUID } from 'node:crypto';
import type { AccountSummary, DeviceRecord, TaskStatus, UsageEvent } from '@cod/contracts';
import { creditPackCatalog, validateDeviceInput, validateTaskTransition, type AuditEntry, type CodDatabase, type CreditGrant, type CreditSummary, type IdentityRecord, type LedgerEntry, type PaymentCompletion, type PaymentOrder, type PaymentOrderRequest, type Principal, type SyncedTask, type TaskEvent, type TaskOutcome, type TopupRequest } from './database.js';
import { HttpError } from './errors.js';
import type { ComputeRequest, ComputeRequestInput } from './compute-market.js';

interface UserState {
  account: AccountSummary;
  ledger: LedgerEntry[];
  idempotency: Map<string, LedgerEntry>;
  devices: Map<string, DeviceRecord>;
  tasks: Map<string, SyncedTask>;
  events: TaskEvent[];
  audit: AuditEntry[];
  reservations: Map<string, { amountCents: number; walletCents: number; grantAllocations: Array<{grantId:string;amountCents:number}>; status: 'reserved' | 'settled' | 'released' }>;
  creditGrants: Map<string,CreditGrant>;
  creditPackIdempotency: Map<string,string>;
  paymentOrders: Map<string, PaymentOrder>;
  paymentIdempotency: Map<string, string>;
  computeRequests: Map<string, ComputeRequest>;
  computeIdempotency: Map<string, string>;
}

export class MemoryDatabase implements CodDatabase {
  private readonly users = new Map<string, UserState>();
  private readonly identities = new Map<string, IdentityRecord>();
  private readonly providerEvents = new Map<string, string>();
  async initialize() {}
  async close() {}
  async health() { return true; }
  async ensurePrincipal(p: Principal) { this.state(p);this.ensureLegacyIdentity(p); }
  async findIdentityByEmail(email:string){return this.identities.get(email.toLowerCase())??null;}
  async registerIdentity(p:Principal,passwordHash:string,inviteCode:string|null,allowExisting:boolean){
    const email=p.email.toLowerCase();const current=this.identities.get(email);
    if(current?.passwordHash)throw new HttpError('该邮箱已经注册，请直接登录',409,'email_registered');
    if(current&&!allowExisting)throw new HttpError('这是旧试点账号，请使用旧访问码完成一次性迁移',409,'legacy_migration_required');
    let inviter:IdentityRecord|null=null;
    if(inviteCode){inviter=[...this.identities.values()].find((identity)=>identity.inviteCode?.toUpperCase()===inviteCode.toUpperCase())??null;if(!inviter)throw new HttpError('邀请码无效',400,'invalid_invite_code');}
    const identity:IdentityRecord={principal:current?.principal??p,passwordHash,inviteCode:current?.inviteCode??`KAI-${p.userId.replace(/^usr_/,'').slice(0,10).toUpperCase()}`,referredByUserId:current?.referredByUserId??inviter?.principal.userId??null,referralCodeUsed:current?.referralCodeUsed??inviter?.inviteCode??null};
    this.state(identity.principal);this.identities.set(email,identity);return{identity,created:!current};
  }
  async getReferralSummary(p:Principal){const identity=this.identities.get(p.email.toLowerCase());if(!identity?.inviteCode)throw new HttpError('Referral profile not found',404,'referral_profile_not_found');return{inviteCode:identity.inviteCode,referredUsers:[...this.identities.values()].filter((item)=>item.referredByUserId===p.userId).length,commissionRateBps:0,pendingCommissionCents:0,settledCommissionCents:0};}
  async getAccount(p: Principal) { return { ...this.state(p).account }; }
  async getLedger(p: Principal) { return [...this.state(p).ledger]; }
  async getCreditSummary(p:Principal):Promise<CreditSummary>{const state=this.state(p);this.expireGrants(state);const grants=[...state.creditGrants.values()].sort((a,b)=>a.expiresAt.localeCompare(b.expiresAt));return{availableCents:grants.filter((grant)=>grant.status==='active').reduce((total,grant)=>total+grant.remainingCents,0),grants:grants.map((grant)=>({...grant}))};}
  async purchaseCreditPack(p:Principal,packId:string,idempotencyKey:string){const state=this.state(p);const pack=creditPackCatalog.find((item)=>item.id===packId);if(!pack)throw new HttpError('Credit pack not found',404,'credit_pack_not_found');if(!idempotencyKey||idempotencyKey.length>200)throw new HttpError('Credit pack idempotency key is invalid',400,'invalid_idempotency_key');const existingId=state.creditPackIdempotency.get(idempotencyKey);if(existingId){const existing=state.creditGrants.get(existingId)!;if(existing.packId!==pack.id)throw new HttpError('Idempotency key was already used with another credit pack',409,'idempotency_conflict');return{grant:{...existing},account:{...state.account},summary:await this.getCreditSummary(p)};}if(state.account.balanceCents<pack.priceCents)throw new HttpError('Insufficient wallet balance',402,'insufficient_balance');const purchasedAt=new Date();const grant:CreditGrant={id:randomUUID(),packId:pack.id,name:pack.name,originalCents:pack.creditCents,remainingCents:pack.creditCents,purchasedAt:purchasedAt.toISOString(),expiresAt:new Date(purchasedAt.getTime()+180*24*60*60*1000).toISOString(),status:'active'};state.account={...state.account,balanceCents:state.account.balanceCents-pack.priceCents};state.creditGrants.set(grant.id,grant);state.creditPackIdempotency.set(idempotencyKey,grant.id);const purchase:LedgerEntry={id:randomUUID(),type:'pack_purchase',amountCents:-pack.priceCents,walletAmountCents:-pack.priceCents,creditAmountCents:0,createdAt:new Date().toISOString(),reference:pack.name,sourceId:null,model:null,paymentDirection:'COD 钱包 → 180 天额度包'};const credit:LedgerEntry={id:randomUUID(),type:'credit_grant',amountCents:pack.creditCents,walletAmountCents:0,creditAmountCents:pack.creditCents,createdAt:new Date().toISOString(),reference:pack.name,sourceId:null,model:null,paymentDirection:'额度包 → COD 使用额度'};state.ledger.unshift(credit,purchase);return{grant:{...grant},account:{...state.account},summary:await this.getCreditSummary(p)};}
  async topup(p: Principal, request: TopupRequest) {
    const state=this.state(p); const existing=state.idempotency.get(request.idempotencyKey); if(existing) return existing;
    if(!Number.isInteger(request.amountCents)||request.amountCents<100||request.amountCents>1_000_000) throw new HttpError('Top-up amount must be between 100 and 1000000 cents',400,'invalid_topup');
    const entry:LedgerEntry={id:randomUUID(),type:'topup',amountCents:request.amountCents,walletAmountCents:request.amountCents,creditAmountCents:0,createdAt:new Date().toISOString(),reference:`${request.channel}:${request.idempotencyKey}`,sourceId:null,model:null,paymentDirection:'用户 → COD 钱包'};
    state.account={...state.account,balanceCents:state.account.balanceCents+request.amountCents}; state.ledger.unshift(entry); state.idempotency.set(request.idempotencyKey,entry); return entry;
  }
  async createPaymentOrder(p: Principal, request: PaymentOrderRequest) {
    const state=this.state(p);
    if(!Number.isInteger(request.amountCents)||request.amountCents<100||request.amountCents>1_000_000)throw new HttpError('Payment amount must be between 100 and 1000000 cents',400,'invalid_payment_amount');
    if(request.channel!=='wechat'&&request.channel!=='alipay')throw new HttpError('Payment channel is invalid',400,'invalid_payment_channel');
    const existingId=state.paymentIdempotency.get(request.idempotencyKey);const existing=existingId?state.paymentOrders.get(existingId):null;
    if(existing){if(existing.amountCents!==request.amountCents||existing.channel!==request.channel)throw new HttpError('Idempotency key was already used with different payment parameters',409,'idempotency_conflict');return existing;}
    const now=new Date().toISOString();const order:PaymentOrder={id:randomUUID(),amountCents:request.amountCents,currency:'CNY',channel:request.channel,status:'pending',providerPaymentId:null,createdAt:now,updatedAt:now};state.paymentOrders.set(order.id,order);state.paymentIdempotency.set(request.idempotencyKey,order.id);return order;
  }
  async getPaymentOrder(p:Principal,orderId:string){const order=this.state(p).paymentOrders.get(orderId);if(!order)throw new HttpError('Payment order not found',404,'payment_order_not_found');return order;}
  async completePaymentOrder(event:PaymentCompletion){
    const eventOrder=this.providerEvents.get(event.providerEventId);if(eventOrder&&eventOrder!==event.orderId)throw new HttpError('Provider payment or event was already used for another order',409,'payment_provider_reused');
    for(const state of this.users.values())for(const order of state.paymentOrders.values())if(order.id!==event.orderId&&order.providerPaymentId===event.providerPaymentId)throw new HttpError('Provider payment or event was already used for another order',409,'payment_provider_reused');
    for(const state of this.users.values()){
      const current=state.paymentOrders.get(event.orderId);if(!current)continue;
      if(current.amountCents!==event.amountCents||current.currency!==event.currency||current.channel!==event.channel)throw new HttpError('Payment event does not match the order',409,'payment_order_mismatch');
      const ledgerKey=`payment-order:${current.id}`;const existing=state.idempotency.get(ledgerKey);
      if(current.status==='paid'){if(current.providerPaymentId!==event.providerPaymentId)throw new HttpError('Payment order is already bound to another provider payment',409,'payment_provider_conflict');if(!existing)throw new HttpError('Paid order ledger entry is missing',500,'payment_ledger_missing');return{order:current,entry:existing};}
      if(current.status!=='pending')throw new HttpError(`Payment order cannot be completed from ${current.status}`,409,'payment_order_not_pending');
      const entry:LedgerEntry={id:randomUUID(),type:'topup',amountCents:current.amountCents,walletAmountCents:current.amountCents,creditAmountCents:0,createdAt:new Date().toISOString(),reference:`${event.channel}:${event.providerPaymentId}`,sourceId:null,model:null,paymentDirection:'用户 → 支付渠道 → COD 钱包'};
      const order:PaymentOrder={...current,status:'paid',providerPaymentId:event.providerPaymentId,updatedAt:new Date().toISOString()};state.account={...state.account,balanceCents:state.account.balanceCents+current.amountCents};state.ledger.unshift(entry);state.idempotency.set(ledgerKey,entry);state.paymentOrders.set(order.id,order);this.providerEvents.set(event.providerEventId,order.id);return{order,entry};
    }
    throw new HttpError('Payment order not found',404,'payment_order_not_found');
  }
  async recordUsage(p: Principal,event:UsageEvent) {
    const state=this.state(p); const existing=state.idempotency.get(event.idempotencyKey); if(existing) return existing;
    if(!Number.isInteger(event.costCents)||event.costCents<0) throw new HttpError('Usage cost is invalid',400,'invalid_usage');
    const allocation=this.allocateFunds(state,event.costCents);const creditCents=allocation.grantAllocations.reduce((total,item)=>total+item.amountCents,0);
    const entry=this.usageEntry(event,allocation.walletCents,creditCents);state.ledger.unshift(entry); state.idempotency.set(event.idempotencyKey,entry); return entry;
  }
  async reserveUsage(p:Principal,id:string,amountCents:number){const state=this.state(p);if(state.reservations.has(id))return;if(!Number.isInteger(amountCents)||amountCents<0)throw new HttpError('Reservation amount is invalid',400,'invalid_reservation');const allocation=this.allocateFunds(state,amountCents);state.reservations.set(id,{amountCents,...allocation,status:'reserved'});}
  async settleUsage(p:Principal,id:string,event:UsageEvent){const state=this.state(p);const reservation=state.reservations.get(id);const existing=state.idempotency.get(event.idempotencyKey);if(existing){if(reservation?.status==='reserved')this.releaseReservation(state,reservation);return existing;}if(!reservation||reservation.status!=='reserved')throw new HttpError('Usage reservation not found',409,'reservation_not_found');let remaining=event.costCents;let creditConsumed=0;for(const allocation of reservation.grantAllocations){const consumed=Math.min(allocation.amountCents,remaining);creditConsumed+=consumed;remaining-=consumed;this.restoreGrant(state,allocation.grantId,allocation.amountCents-consumed);}const walletConsumed=Math.min(reservation.walletCents,remaining);remaining-=walletConsumed;state.account={...state.account,balanceCents:state.account.balanceCents+reservation.walletCents-walletConsumed};let totalWallet=walletConsumed;if(remaining>0){const extra=this.allocateFunds(state,remaining);totalWallet+=extra.walletCents;creditConsumed+=extra.grantAllocations.reduce((total,item)=>total+item.amountCents,0);}const entry=this.usageEntry(event,totalWallet,creditConsumed);state.ledger.unshift(entry);state.idempotency.set(event.idempotencyKey,entry);reservation.status='settled';return entry;}
  async releaseUsage(p:Principal,id:string){const state=this.state(p);const reservation=state.reservations.get(id);if(!reservation||reservation.status!=='reserved')return;this.releaseReservation(state,reservation);}
  async createComputeRequest(p:Principal,input:ComputeRequestInput,idempotencyKey:string){const state=this.state(p);if(!idempotencyKey||idempotencyKey.length>200)throw new HttpError('Compute request idempotency key is invalid',400,'invalid_idempotency_key');const existingId=state.computeIdempotency.get(idempotencyKey);if(existingId)return{...state.computeRequests.get(existingId)!};const now=new Date().toISOString();const request:ComputeRequest={...input,id:randomUUID(),email:p.email,offerId:input.offerId??null,durationHours:input.durationHours??null,termMonths:input.termMonths??null,status:'submitted',createdAt:now,updatedAt:now};state.computeRequests.set(request.id,request);state.computeIdempotency.set(idempotencyKey,request.id);return{...request};}
  async listComputeRequests(p:Principal){return[...this.state(p).computeRequests.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map((request)=>({...request}));}
  async listDevices(p:Principal){return [...this.state(p).devices.values()].map((device)=>Date.now()-new Date(device.lastSeenAt).getTime()>45_000?{...device,status:'offline' as const}:device);}
  async registerDevice(p:Principal,input:Pick<DeviceRecord,'name'|'platform'>){validateDeviceInput(input);const state=this.state(p);const device:DeviceRecord={id:randomUUID(),name:input.name.trim().slice(0,100),platform:input.platform,status:'online',lastSeenAt:new Date().toISOString()};state.devices.set(device.id,device);this.append(state,'device.registered',device.id,device);return device;}
  async heartbeat(p:Principal,id:string){const state=this.state(p);const current=state.devices.get(id);if(!current)throw new HttpError('Device not found',404,'device_not_found');const device={...current,status:'online' as const,lastSeenAt:new Date().toISOString()};state.devices.set(id,device);return device;}
  async listTasks(p:Principal){return [...this.state(p).tasks.values()];}
  async createTask(p:Principal,input:Pick<SyncedTask,'title'|'deviceId'>){const state=this.state(p);if(!input.title?.trim())throw new HttpError('Task title is required',400,'invalid_task');if(!state.devices.has(input.deviceId))throw new HttpError('Device not found',404,'device_not_found');const task:SyncedTask={id:randomUUID(),title:input.title.trim().slice(0,500),deviceId:input.deviceId,status:'draft',updatedAt:new Date().toISOString(),version:1,result:null,error:null};state.tasks.set(task.id,task);this.append(state,'task.created',task.id,task);return task;}
  async updateTask(p:Principal,id:string,status:TaskStatus,version:number,outcome:TaskOutcome={}){const state=this.state(p);const current=state.tasks.get(id);if(!current)throw new HttpError('Task not found',404,'task_not_found');if(current.version!==version)throw new HttpError('Task version conflict',409,'version_conflict');validateTaskTransition(current.status,status);if(outcome.result!==undefined&&outcome.result!==null&&outcome.result.length>50_000)throw new HttpError('Task result is too large',400,'task_result_too_large');if(outcome.error!==undefined&&outcome.error!==null&&outcome.error.length>5_000)throw new HttpError('Task error is too large',400,'task_error_too_large');if(current.status===status&&outcome.result===undefined&&outcome.error===undefined)return current;const task={...current,status,result:outcome.result===undefined?current.result:outcome.result,error:outcome.error===undefined?current.error:outcome.error,version:current.version+1,updatedAt:new Date().toISOString()};state.tasks.set(id,task);this.append(state,'task.updated',id,task);return task;}
  async eventsAfter(p:Principal,cursor:number){return this.state(p).events.filter((event)=>event.cursor>cursor);}
  async audit(p:Principal,action:string,entityType:string,entityId:string|null,data:unknown={}){this.state(p).audit.unshift({id:randomUUID(),action,entityType,entityId,data,createdAt:new Date().toISOString()});}
  async listAudit(p:Principal,limit:number){return this.state(p).audit.slice(0,Math.min(Math.max(limit,1),200));}
  private key(p:Principal){return `${p.tenantId}:${p.userId}`;}
  private ensureLegacyIdentity(p:Principal){const email=p.email.toLowerCase();if(!this.identities.has(email))this.identities.set(email,{principal:p,passwordHash:null,inviteCode:`KAI-${p.userId.replace(/^usr_/,'').slice(0,10).toUpperCase()}`,referredByUserId:null,referralCodeUsed:null});}
  private state(p:Principal){const key=this.key(p);let state=this.users.get(key);if(!state){const now=new Date();const trial:CreditGrant={id:randomUUID(),packId:'trial',name:'新用户试用金',originalCents:1000,remainingCents:1000,purchasedAt:now.toISOString(),expiresAt:new Date(now.getTime()+30*24*60*60*1000).toISOString(),status:'active'};const trialEntry:LedgerEntry={id:randomUUID(),type:'trial_credit',amountCents:1000,walletAmountCents:0,creditAmountCents:1000,createdAt:now.toISOString(),reference:'新用户试用金',sourceId:null,model:null,paymentDirection:'平台赠送 → COD 使用额度'};state={account:{userId:p.userId,displayName:p.email.split('@')[0],balanceCents:0,currency:'CNY',plan:'developer'},ledger:[trialEntry],idempotency:new Map(),devices:new Map(),tasks:new Map(),events:[],audit:[],reservations:new Map(),creditGrants:new Map([[trial.id,trial]]),creditPackIdempotency:new Map(),paymentOrders:new Map(),paymentIdempotency:new Map(),computeRequests:new Map(),computeIdempotency:new Map()};this.users.set(key,state);}return state;}
  private expireGrants(state:UserState){for(const [id,grant] of state.creditGrants)if(grant.status==='active'&&new Date(grant.expiresAt).getTime()<=Date.now())state.creditGrants.set(id,{...grant,status:'expired'});}
  private allocateFunds(state:UserState,amountCents:number){this.expireGrants(state);let remaining=amountCents;const grantAllocations:Array<{grantId:string;amountCents:number}>=[];const active=[...state.creditGrants.values()].filter((grant)=>grant.status==='active'&&grant.remainingCents>0).sort((a,b)=>a.expiresAt.localeCompare(b.expiresAt));for(const grant of active){if(remaining<=0)break;const amount=Math.min(grant.remainingCents,remaining);grantAllocations.push({grantId:grant.id,amountCents:amount});remaining-=amount;state.creditGrants.set(grant.id,{...grant,remainingCents:grant.remainingCents-amount,status:grant.remainingCents===amount?'depleted':'active'});}if(state.account.balanceCents<remaining){for(const allocation of grantAllocations)this.restoreGrant(state,allocation.grantId,allocation.amountCents);throw new HttpError('Insufficient balance',402,'insufficient_balance');}state.account={...state.account,balanceCents:state.account.balanceCents-remaining};return{walletCents:remaining,grantAllocations};}
  private restoreGrant(state:UserState,grantId:string,amountCents:number){if(amountCents<=0)return;const grant=state.creditGrants.get(grantId);if(!grant)return;const remainingCents=Math.min(grant.originalCents,grant.remainingCents+amountCents);state.creditGrants.set(grantId,{...grant,remainingCents,status:new Date(grant.expiresAt).getTime()<=Date.now()?'expired':'active'});}
  private releaseReservation(state:UserState,reservation:{walletCents:number;grantAllocations:Array<{grantId:string;amountCents:number}>;status:'reserved'|'settled'|'released'}){state.account={...state.account,balanceCents:state.account.balanceCents+reservation.walletCents};for(const allocation of reservation.grantAllocations)this.restoreGrant(state,allocation.grantId,allocation.amountCents);reservation.status='released';}
  private usageEntry(event:UsageEvent,walletCents:number,creditCents:number):LedgerEntry{return{id:randomUUID(),type:'usage',amountCents:event.costCents?-event.costCents:0,walletAmountCents:walletCents?-walletCents:0,creditAmountCents:creditCents?-creditCents:0,createdAt:new Date().toISOString(),reference:`${event.sourceId}:${event.model}:${event.taskId}`,sourceId:event.sourceId,upstreamSourceId:event.upstreamSourceId??'ai-kai',model:event.model,paymentDirection:event.paymentDirection,commissionRateBps:event.commissionRateBps??0,commissionCents:event.commissionCents??0};}
  private append(state:UserState,type:TaskEvent['type'],entityId:string,data:unknown){state.events.push({cursor:state.events.length+1,type,entityId,data,createdAt:new Date().toISOString()});}
}
