import type { ComputeCapabilities, ComputeDeliveryMode, ComputeOfferV2 } from '@cod/contracts/compute-market-v2';
import { ComputeCatalogService, defaultComputeCapabilities } from './catalog.js';

const RUNPOD_PRICING = 'https://www.runpod.io/pricing';
const LAMBDA_PRICING = 'https://lambda.ai/instances';
const AWS_CAPACITY_BLOCKS = 'https://aws.amazon.com/ec2/capacityblocks/pricing/';

export const computeShowcaseCapabilities: ComputeCapabilities = {
  ...defaultComputeCapabilities,
  enabled: true,
};

const media = (id: string, model: string): ComputeOfferV2['media'] => [{
  id: `${id}-media`,
  url: '/compute/gpu-accelerator.webp',
  alt: `${model} 无品牌 GPU 加速卡方案展示图`,
}];

function showcaseOffer(input: {
  id: string;
  title: string;
  model: string;
  memoryGb: number;
  gpuCount?: number;
  deliveryMode: ComputeDeliveryMode;
  cpuCores?: number;
  ramGb?: number;
  systemDiskGb?: number;
  dataDiskGb?: number;
  networkLabel?: string;
  storageLabel?: string;
  gpuInterconnectLabel?: string;
  powerLabel?: string;
  priceCardHoursMilli?: number | null;
  referencePriceUsd: { low: number; high: number; basis: string; sources: Array<{ provider: string; url: string }> };
  tags: string[];
  framework: string;
  frameworkVersion: string;
  pythonVersion: string;
  cudaVersion: string;
  updatedAt: string;
}): ComputeOfferV2 {
  return {
    id: input.id,
    slug: input.id,
    title: input.title,
    status: 'published',
    purchaseMode: 'instant',
    providerName: 'COD 认证算力节点',
    regionLabel: '全国可调度区域',
    gpu: { model: input.model, memoryGb: input.memoryGb, countPerUnit: input.gpuCount ?? 1 },
    specs: {
      cpuModel: '参考配置 · AMD EPYC',
      cpuCores: input.cpuCores ?? 16,
      ramGb: input.ramGb ?? 128,
      systemDiskGb: input.systemDiskGb ?? 100,
      dataDiskGb: input.dataDiskGb ?? 500,
      driverVersion: '交付前确认',
      cudaVersion: input.cudaVersion,
      networkLabel: input.networkLabel ?? '交付前确认',
      storageLabel: input.storageLabel ?? '本地 NVMe SSD',
      gpuInterconnectLabel: input.gpuInterconnectLabel ?? '交付前确认',
      powerLabel: input.powerLabel ?? '节点功耗交付前确认',
    },
    tags: input.tags,
    media: media(input.id, input.model),
    skus: [{
      id: `${input.id}-hour`,
      offerId: input.id,
      deliveryMode: input.deliveryMode,
      period: 'hour',
      minimumUnits: 1,
      maximumUnits: 8,
      priceCardHoursMilli: input.priceCardHoursMilli ?? null,
      compareAtPriceCardHoursMilli: null,
      inventoryRevision: 1,
      imageOptions: [{
        id: `${input.id}-image`,
        label: `${input.framework} ${input.frameworkVersion} · Python ${input.pythonVersion}`,
        framework: input.framework,
        frameworkVersion: input.frameworkVersion,
        pythonVersion: input.pythonVersion,
        cudaVersion: input.cudaVersion,
        operatingSystem: 'Ubuntu 22.04 LTS',
        containerRuntime: input.deliveryMode === 'bare_metal' ? '裸金属，可选 Docker 与 NVIDIA Container Toolkit' : 'Docker + NVIDIA Container Toolkit',
        includedSoftware: [input.framework, 'JupyterLab', 'NCCL'],
      }, {
        id: `${input.id}-clean-image`,
        label: '纯净 Ubuntu · 自定义环境',
        framework: '纯净环境',
        frameworkVersion: '',
        pythonVersion: input.pythonVersion,
        cudaVersion: input.cudaVersion,
        operatingSystem: 'Ubuntu 22.04 LTS',
        containerRuntime: '可自行安装 Docker、PyTorch、vLLM 或 ComfyUI',
        includedSoftware: [],
      }],
    }],
    availability: { level: 'ready', label: '价格公开' },
    priceReference: {
      currency: 'USD',
      unit: 'gpu_hour',
      low: input.referencePriceUsd.low,
      high: input.referencePriceUsd.high,
      observedAt: '2026-08-15',
      basis: input.referencePriceUsd.basis,
      sources: input.referencePriceUsd.sources,
    },
    updatedAt: input.updatedAt,
  };
}

export const computeShowcaseOffers: ComputeOfferV2[] = [
  showcaseOffer({
    id: 'showcase-b300-288g',
    title: 'B300 / 288 GB',
    model: 'B300',
    memoryGb: 288,
    deliveryMode: 'bare_metal',
    priceCardHoursMilli: 44_000,
    referencePriceUsd: { low: 9.98, high: 9.98, basis: 'RunPod B300 Serverless 公开按小时价格，裸金属整机需单独询价', sources: [{ provider: 'RunPod', url: RUNPOD_PRICING }] },
    storageLabel: '8 卡节点本地 NVMe，容量交付前确认',
    gpuInterconnectLabel: 'B300 SXM · NVLink / NVSwitch 拓扑交付前确认',
    powerLabel: '裸金属整机，机柜功耗交付前确认',
    tags: ['训练', '推理', '科研'],
    framework: 'PyTorch',
    frameworkVersion: '2.x',
    pythonVersion: '3.x',
    cudaVersion: '交付前确认',
    updatedAt: '2026-08-15T04:00:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-h200-141g',
    title: 'H200 SXM / 141 GB',
    model: 'H200',
    memoryGb: 141,
    deliveryMode: 'bare_metal',
    cpuCores: 64,
    ramGb: 512,
    systemDiskGb: 200,
    dataDiskGb: 2_000,
    networkLabel: '100G 以太网 / IB 可选',
    storageLabel: '企业级 NVMe，可挂载共享存储',
    gpuInterconnectLabel: 'SXM · NVLink 900 GB/s',
    powerLabel: '单卡最高 700W，整机功耗交付前确认',
    priceCardHoursMilli: 26_000,
    referencePriceUsd: { low: 4.98, high: 5.93, basis: 'AWS Capacity Blocks 与 RunPod 公开 H200 按小时价格区间', sources: [{ provider: 'AWS', url: AWS_CAPACITY_BLOCKS }, { provider: 'RunPod', url: RUNPOD_PRICING }] },
    tags: ['训练', '推理', '高速互联'],
    framework: 'PyTorch',
    frameworkVersion: '2.x',
    pythonVersion: '3.x',
    cudaVersion: '12.x',
    updatedAt: '2026-08-15T03:30:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-h100-1x80g',
    title: '1× H100 / 80 GB',
    model: 'H100',
    memoryGb: 80,
    deliveryMode: 'virtual_machine',
    cpuCores: 28,
    ramGb: 120,
    systemDiskGb: 100,
    dataDiskGb: 750,
    networkLabel: '10G',
    priceCardHoursMilli: 20_000,
    referencePriceUsd: { low: 3.93, high: 4.55, basis: 'AWS、Lambda 与 RunPod 公开 H100 按小时价格区间', sources: [{ provider: 'AWS', url: AWS_CAPACITY_BLOCKS }, { provider: 'Lambda', url: LAMBDA_PRICING }, { provider: 'RunPod', url: RUNPOD_PRICING }] },
    gpuInterconnectLabel: '独占 GPU · PCIe / NVLink 以节点为准',
    tags: ['训练', '推理', '科研'],
    framework: 'PyTorch',
    frameworkVersion: '2.x',
    pythonVersion: '3.x',
    cudaVersion: '交付前确认',
    updatedAt: '2026-08-13T03:00:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-h100-2x80g',
    title: '2× H100 / 80 GB',
    model: 'H100',
    memoryGb: 80,
    gpuCount: 2,
    deliveryMode: 'virtual_machine',
    cpuCores: 60,
    ramGb: 240,
    systemDiskGb: 100,
    dataDiskGb: 1_500,
    networkLabel: '10G',
    priceCardHoursMilli: 40_000,
    referencePriceUsd: { low: 3.93, high: 4.55, basis: '按单卡折算，参考 AWS、Lambda 与 RunPod 公开价格', sources: [{ provider: 'AWS', url: AWS_CAPACITY_BLOCKS }, { provider: 'Lambda', url: LAMBDA_PRICING }, { provider: 'RunPod', url: RUNPOD_PRICING }] },
    gpuInterconnectLabel: '2 卡独占 · NVLink 拓扑交付前确认',
    tags: ['训练', '推理', '科研'],
    framework: 'PyTorch',
    frameworkVersion: '2.x',
    pythonVersion: '3.x',
    cudaVersion: '交付前确认',
    updatedAt: '2026-08-13T02:50:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-h100-4x80g',
    title: '4× H100 / 80 GB',
    model: 'H100',
    memoryGb: 80,
    gpuCount: 4,
    deliveryMode: 'virtual_machine',
    cpuCores: 124,
    ramGb: 480,
    systemDiskGb: 100,
    dataDiskGb: 3_200,
    networkLabel: '10G',
    priceCardHoursMilli: 80_000,
    referencePriceUsd: { low: 3.93, high: 4.55, basis: '按单卡折算，参考 AWS、Lambda 与 RunPod 公开价格', sources: [{ provider: 'AWS', url: AWS_CAPACITY_BLOCKS }, { provider: 'Lambda', url: LAMBDA_PRICING }, { provider: 'RunPod', url: RUNPOD_PRICING }] },
    gpuInterconnectLabel: '4 卡独占 · NVLink 拓扑交付前确认',
    tags: ['训练', '推理', '科研'],
    framework: 'PyTorch',
    frameworkVersion: '2.x',
    pythonVersion: '3.x',
    cudaVersion: '交付前确认',
    updatedAt: '2026-08-13T02:40:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-h100-8x80g',
    title: '8× H100 / 80 GB',
    model: 'H100',
    memoryGb: 80,
    gpuCount: 8,
    deliveryMode: 'virtual_machine',
    cpuCores: 252,
    ramGb: 1_440,
    systemDiskGb: 100,
    dataDiskGb: 6_500,
    networkLabel: '10G',
    priceCardHoursMilli: 160_000,
    referencePriceUsd: { low: 3.93, high: 4.55, basis: '按单卡折算，参考 AWS、Lambda 与 RunPod 公开价格', sources: [{ provider: 'AWS', url: AWS_CAPACITY_BLOCKS }, { provider: 'Lambda', url: LAMBDA_PRICING }, { provider: 'RunPod', url: RUNPOD_PRICING }] },
    gpuInterconnectLabel: '8 卡 HGX 节点 · NVLink / NVSwitch',
    tags: ['训练', '推理', '科研'],
    framework: 'PyTorch',
    frameworkVersion: '2.x',
    pythonVersion: '3.x',
    cudaVersion: '交付前确认',
    updatedAt: '2026-08-13T02:30:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-a100-80g',
    title: 'A100 SXM / 80 GB',
    model: 'A100',
    memoryGb: 80,
    deliveryMode: 'virtual_machine',
    cpuCores: 30,
    ramGb: 220,
    systemDiskGb: 100,
    dataDiskGb: 1_000,
    networkLabel: '10G，集群网络另询',
    gpuInterconnectLabel: 'SXM / PCIe 形态以节点为准',
    priceCardHoursMilli: 13_600,
    referencePriceUsd: { low: 2.72, high: 2.79, basis: 'Lambda 与 RunPod 公开 A100 80 GB 按小时价格区间', sources: [{ provider: 'Lambda', url: LAMBDA_PRICING }, { provider: 'RunPod', url: RUNPOD_PRICING }] },
    tags: ['训练', '推理', '模型微调'],
    framework: 'PyTorch',
    frameworkVersion: '2.x',
    pythonVersion: '3.x',
    cudaVersion: '12.x',
    updatedAt: '2026-08-15T02:20:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-l40s-48g',
    title: 'L40S / 48 GB',
    model: 'L40S',
    memoryGb: 48,
    deliveryMode: 'container',
    priceCardHoursMilli: 7_700,
    referencePriceUsd: { low: 1.75, high: 1.75, basis: 'RunPod L40 / L40S Serverless 公开按小时价格', sources: [{ provider: 'RunPod', url: RUNPOD_PRICING }] },
    gpuInterconnectLabel: 'PCIe Gen4 x16 · 不支持 NVLink',
    powerLabel: '350W TDP，节点功耗以交付为准',
    tags: ['推理', '生成式AI', '渲染'],
    framework: 'ComfyUI',
    frameworkVersion: '交付版',
    pythonVersion: '3.x',
    cudaVersion: '交付前确认',
    updatedAt: '2026-08-15T01:20:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-rtx-4090-24g',
    title: 'RTX 4090 / 24 GB',
    model: 'RTX 4090',
    memoryGb: 24,
    deliveryMode: 'container',
    cpuCores: 16,
    ramGb: 128,
    systemDiskGb: 100,
    dataDiskGb: 500,
    networkLabel: '1G 公网带宽可选',
    gpuInterconnectLabel: 'PCIe 独占卡 · 不支持 NVLink',
    priceCardHoursMilli: 4_800,
    referencePriceUsd: { low: 1.10, high: 1.10, basis: 'RunPod RTX 4090 Serverless 公开按小时价格', sources: [{ provider: 'RunPod', url: RUNPOD_PRICING }] },
    tags: ['生成式AI', '渲染', '开发'],
    framework: 'ComfyUI',
    frameworkVersion: '交付版',
    pythonVersion: '3.x',
    cudaVersion: '12.x',
    updatedAt: '2026-08-15T01:30:00.000Z',
  }),
  showcaseOffer({
    id: 'showcase-rtx-5090-32g',
    title: 'RTX 5090 / 32 GB',
    model: 'RTX 5090',
    memoryGb: 32,
    deliveryMode: 'container',
    priceCardHoursMilli: 7_000,
    referencePriceUsd: { low: 1.58, high: 1.58, basis: 'RunPod RTX 5090 Serverless 公开按小时价格', sources: [{ provider: 'RunPod', url: RUNPOD_PRICING }] },
    gpuInterconnectLabel: 'PCIe 独占卡 · 不支持 NVLink',
    tags: ['生成式AI', '渲染', '推理'],
    framework: 'PyTorch',
    frameworkVersion: '2.x',
    pythonVersion: '3.x',
    cudaVersion: '交付前确认',
    updatedAt: '2026-08-15T01:00:00.000Z',
  }),
];

export function createComputeShowcaseCatalog(): ComputeCatalogService {
  return new ComputeCatalogService(computeShowcaseCapabilities, computeShowcaseOffers);
}
