import type { ComputeAdminDashboard } from '@cod/contracts/compute-market-v2';
import { ArrowLeft, ChartBar, ClipboardText, Cpu, HardDrives, ListMagnifyingGlass, Newspaper, Package, ShieldCheck, Storefront, Ticket } from '@phosphor-icons/react';
import { useMemo, useState } from 'react';
import { createComputeApi } from './api';
import { ErrorState } from './components/ErrorState';
import { EmptyState } from './components/EmptyState';
import { useComputeResource } from './hooks/useComputeResource';
import type { ComputeSession } from './types';
import './compute-market.css';

export interface ComputeAdminAppProps { session: ComputeSession; initialPath: string; onExit(): void }
type Section = 'dashboard' | 'catalog' | 'inventory' | 'orders' | 'hosting' | 'devices' | 'tickets' | 'content' | 'audit';
interface WorkItem { id: string; title: string; subtitle: string; status: string; revision?: number; raw: unknown }

const navigation: Array<{ section: Section; label: string; icon: typeof ChartBar }> = [
  { section: 'dashboard', label: '总览', icon: ChartBar }, { section: 'catalog', label: '商品', icon: Storefront }, { section: 'inventory', label: '库存', icon: HardDrives },
  { section: 'orders', label: '订单', icon: Package }, { section: 'hosting', label: '托管', icon: ClipboardText }, { section: 'devices', label: '设备', icon: Cpu },
  { section: 'tickets', label: '工单', icon: Ticket }, { section: 'content', label: '内容', icon: Newspaper }, { section: 'audit', label: '审计', icon: ShieldCheck },
];

export function ComputeAdminApp({ session, initialPath, onExit }: ComputeAdminAppProps) {
  const section = (initialPath.split('/').filter(Boolean).at(-1) as Section) || 'dashboard'; const [current, setCurrent] = useState<Section>(navigation.some((item) => item.section === section) ? section : 'dashboard');
  const api = useMemo(() => createComputeApi({ token: session.token }), [session.token]);
  return <div className="compute-app compute-admin-app"><aside className="compute-admin-nav"><div><strong>COD</strong><span>算力运营台</span></div><nav>{navigation.map((item) => <button type="button" className={current === item.section ? 'active' : ''} key={item.section} onClick={() => setCurrent(item.section)}><item.icon /><span>{item.label}</span></button>)}</nav><button type="button" onClick={onExit}><ArrowLeft /> 返回 COD</button></aside><div className="compute-admin-main"><header><div><h1>{navigation.find((item) => item.section === current)?.label}</h1><p>算力市场 / 运营管理</p></div><span>{session.account.displayName}</span></header><main>{current === 'dashboard' ? <AdminDashboard api={api} open={setCurrent} /> : <AdminWorkbench api={api} section={current} />}</main></div></div>;
}

function AdminDashboard({ api, open }: { api: ReturnType<typeof createComputeApi>; open: (section: Section) => void }) {
  const resource = useComputeResource((signal) => api.admin.dashboard(signal), [api]); if (resource.state === 'error') return <ErrorState message={resource.error?.message} onRetry={resource.reload} />; if (!resource.data) return <div className="compute-skeleton list" />;
  const cards: Array<[keyof ComputeAdminDashboard, string, Section]> = [['newOrders', '今日新订单', 'orders'], ['pendingQuotes', '待报价', 'orders'], ['pendingDeployments', '待部署', 'orders'], ['runningInstances', '运行实例', 'orders'], ['actionRequiredDevices', '异常设备', 'devices'], ['expiringReservations', '即将到期预占', 'inventory'], ['openTickets', '待处理工单', 'tickets']];
  return <div className="compute-admin-dashboard">{cards.map(([key, label, section]) => <button type="button" key={key} onClick={() => open(section)}><span>{label}</span><strong>{resource.data?.[key]}</strong><small>查看队列 →</small></button>)}</div>;
}

function AdminWorkbench({ api, section }: { api: ReturnType<typeof createComputeApi>; section: Exclude<Section, 'dashboard'> }) {
  const resource = useComputeResource(async (signal) => {
    if (section === 'catalog') return (await api.admin.catalog(signal)).items.map((record): WorkItem => ({ id: record.offer.id, title: record.offer.title, subtitle: `${record.offer.gpu.model} · ${record.offer.regionLabel}`, status: record.offer.status, revision: record.revision, raw: record }));
    if (section === 'inventory') return (await api.admin.inventory(signal)).items.map((pool): WorkItem => ({ id: pool.id, title: pool.skuId, subtitle: `${pool.nodeLabel} · ${pool.facilityLabel}`, status: `${pool.availableUnits} 可用`, revision: pool.revision, raw: pool }));
    if (section === 'orders') return (await api.admin.orders(signal)).items.map((order): WorkItem => ({ id: order.id, title: order.skuSnapshot.offerTitle, subtitle: `${order.contact.name} · ${order.contact.phone}`, status: order.status, revision: order.revision, raw: order }));
    if (section === 'hosting') return (await api.admin.hosting(signal)).items.map((item): WorkItem => ({ id: item.id, title: item.devices[0]?.gpuModel || '设备资料待完善', subtitle: `${item.contactName} · ${item.contactPhone}`, status: item.status, revision: item.revision, raw: item }));
    if (section === 'devices') return (await api.admin.devices(signal)).items.map((device): WorkItem => ({ id: device.id, title: device.name, subtitle: `${device.gpuModel} · ${device.gpuCount} 卡`, status: device.status, revision: device.revision, raw: device }));
    if (section === 'tickets') return (await api.admin.tickets(signal)).items.map((ticket): WorkItem => ({ id: ticket.id, title: ticket.subject, subtitle: ticket.category, status: ticket.status, raw: ticket }));
    if (section === 'content') return (await api.admin.content(signal)).items.map((record): WorkItem => ({ id: record.entry.id, title: record.entry.title, subtitle: record.entry.category, status: record.status, revision: record.revision, raw: record }));
    return (await api.admin.audit(signal)).items.map((event): WorkItem => ({ id: event.id, title: event.action, subtitle: `${event.entityType} · ${event.entityId ?? '-'}`, status: new Date(event.createdAt).toLocaleString('zh-CN'), raw: event }));
  }, [api, section]);
  const [query, setQuery] = useState(''); const [selectedId, setSelectedId] = useState(''); const items = resource.data ?? []; const filtered = items.filter((item) => `${item.title} ${item.subtitle} ${item.status}`.toLowerCase().includes(query.toLowerCase())); const selected = items.find((item) => item.id === selectedId) ?? filtered[0];
  if (resource.state === 'error') return <ErrorState message={resource.error?.message} onRetry={resource.reload} />;
  return <div className="compute-admin-workbench"><aside className="compute-admin-filters"><strong>筛选 / 队列</strong><label><ListMagnifyingGlass /><input aria-label="搜索管理队列" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ID、状态、型号" /></label><button type="button" onClick={() => setQuery('')}>清除条件</button><p>列表只显示脱敏摘要；敏感信息不得进入分析事件或普通日志。</p></aside><section className="compute-admin-list"><div><strong>{filtered.length} 项</strong><button type="button" onClick={resource.reload}>刷新</button></div>{!resource.data ? <div className="compute-skeleton list" /> : filtered.length ? filtered.map((item) => <button type="button" className={selected?.id === item.id ? 'active' : ''} key={item.id} onClick={() => setSelectedId(item.id)}><span>{item.status}</span><strong>{item.title}</strong><small>{item.subtitle}</small><code>{item.id.slice(-12)}</code></button>) : <EmptyState title="当前队列为空" description="没有真实记录时不展示占位数据。" />}</section><aside className="compute-admin-detail">{selected ? <AdminRecordDetail api={api} section={section} item={selected} reload={resource.reload} /> : <EmptyState title="选择一条记录" description="右侧将显示对象、当前状态、目标状态和影响。" />}</aside></div>;
}

function AdminRecordDetail({ api, section, item, reload }: { api: ReturnType<typeof createComputeApi>; section: Exclude<Section, 'dashboard'>; item: WorkItem; reload: () => void }) {
  const [reason, setReason] = useState(''); const [target, setTarget] = useState(item.status); const [confirming, setConfirming] = useState(false); const [message, setMessage] = useState('');
  const options = section === 'orders' ? ['quoted', 'provisioning', 'running', 'action_required', 'completed', 'refund_pending'] : section === 'hosting' ? ['reviewing', 'site_survey', 'quoted', 'contract_pending', 'inbound_pending', 'deploying', 'running', 'action_required', 'offboarding', 'completed', 'rejected'] : section === 'devices' ? ['deploying', 'running', 'action_required', 'maintenance', 'offline', 'retired'] : section === 'catalog' ? ['draft', 'published', 'paused', 'sold_out', 'archived'] : section === 'content' ? ['draft', 'scheduled', 'published', 'withdrawn'] : [];
  const execute = async () => { setMessage(''); try { if (section === 'orders') await api.admin.transitionOrder(item.raw as never, target as never, reason); else if (section === 'hosting') await api.admin.transitionHosting(item.raw as never, target as never, reason, '请按新状态查看下一步', target === 'action_required' ? 'user' : 'cod'); else if (section === 'devices') await api.admin.transitionDevice(item.raw as never, target as never, reason, target === 'action_required' ? '请联系运营处理设备异常' : null); else if (section === 'catalog') { const record = structuredClone(item.raw) as Parameters<typeof api.admin.saveOffer>[0]; record.offer.status = target as never; await api.admin.saveOffer(record, reason); } else if (section === 'content') { const record = structuredClone(item.raw) as Parameters<typeof api.admin.saveContent>[0]; record.status = target as never; await api.admin.saveContent(record, reason); } setMessage('操作已完成并记录审计。'); setConfirming(false); reload(); } catch (error) { setMessage(error instanceof Error ? error.message : '操作失败'); } };
  const summary = item.raw as Record<string, unknown>;
  return <div><header><span>{item.status}</span><h2>{item.title}</h2><code>{item.id}</code></header><dl><div><dt>当前状态</dt><dd>{item.status}</dd></div>{item.revision && <div><dt>数据版本</dt><dd>{item.revision}</dd></div>}<div><dt>摘要</dt><dd>{item.subtitle}</dd></div></dl>{section === 'audit' ? <pre>{JSON.stringify(summary.summary ?? summary, null, 2)}</pre> : section === 'tickets' ? <p>工单处理写操作将在接入专用工单状态机后由 capability 开放。</p> : options.length ? <section className="compute-admin-action"><h3>状态操作</h3><label>目标状态<select value={target} onChange={(event) => { setTarget(event.target.value); setConfirming(false); }}>{options.map((option) => <option key={option}>{option}</option>)}</select></label><label>操作原因<textarea value={reason} onChange={(event) => { setReason(event.target.value); setConfirming(false); }} placeholder="必填：说明依据和影响" /></label>{confirming ? <div className="compute-admin-confirm"><p>对象：{item.title}<br />当前：{item.status}<br />目标：{target}<br />影响：写入状态事件与只读审计记录。</p><button type="button" className="compute-button primary" onClick={execute}>确认执行</button><button type="button" className="compute-button secondary" onClick={() => setConfirming(false)}>返回修改</button></div> : <button type="button" className="compute-button primary" disabled={reason.trim().length < 4 || target === item.status} onClick={() => setConfirming(true)}>检查影响</button>}</section> : <p>该队列当前为只读。库存数量调整需通过带 expectedRevision、幂等键和原因的专用表单。</p>}{message && <p role="status">{message}</p>}</div>;
}
