import { CalendarBlank, HardDrives, MapPin } from '@phosphor-icons/react';
import { useState } from 'react';
import { formatCardHours, periodLabel } from '../api';
import { ErrorState } from '../components/ErrorState';
import { PriceBreakdown } from '../components/PriceBreakdown';
import { useComputeResource } from '../hooks/useComputeResource';
import type { ComputePageProps } from './shared';

export function CheckoutPage({ api, navigate, skuId, query }: ComputePageProps & { skuId: string; query: URLSearchParams }) {
  const resource = useComputeResource(async (signal) => { const offer = await api.offer(query.get('offerId') ?? '', signal); const sku = offer.skus.find((item) => item.id === skuId); if (!sku) throw new Error('所选 SKU 不存在'); return { offer, sku }; }, [skuId, query.toString()]);
  const [contactName, setContactName] = useState(''); const [contactPhone, setContactPhone] = useState(''); const [accepted, setAccepted] = useState(false); const [submitting, setSubmitting] = useState(false); const [submitError, setSubmitError] = useState('');
  if (resource.state === 'error') return <ErrorState message={resource.error?.message} onRetry={resource.reload} />;
  if (!resource.data) return <div className="compute-skeleton detail-card" />;
  const { offer, sku } = resource.data; const quantity = Math.max(sku.minimumUnits, Number(query.get('quantity') ?? sku.minimumUnits)); const duration = Math.max(1, Number(query.get('duration') ?? 1)); const image = sku.imageOptions.find((item) => item.id === query.get('imageId')) ?? sku.imageOptions[0]; const startsAtRaw = query.get('startsAt') ?? ''; const quote = offer.purchaseMode === 'quote' || offer.availability.level === 'quote'; const subtotal = (sku.priceCardHoursMilli ?? 0) * quantity * duration;
  const submit = async () => { if (!accepted || !contactName.trim() || !contactPhone.trim()) { setSubmitError('请完善联系人并确认责任边界与服务条款。'); return; } setSubmitting(true); setSubmitError(''); try { const order = await api.createOrder({ skuId: sku.id, imageId: image.id, quantity, availableDurationHours: duration, startsAt: startsAtRaw ? new Date(startsAtRaw).toISOString() : null, inventoryRevision: sku.inventoryRevision, contact: { name: contactName, phone: contactPhone }, acceptedTermsVersion: 'compute-terms-2026-08-13' }); navigate(`/compute/orders/${order.id}`); } catch (error) { setSubmitError(error instanceof Error ? error.message : '提交失败'); } finally { setSubmitting(false); } };
  return <div className="compute-checkout-layout"><div className="compute-checkout-main"><section className="compute-panel compute-order-summary"><img src={offer.media[0]?.url} alt="" /><div><span>{offer.availability.label}</span><h2>{offer.title}</h2><p><HardDrives /> {image.label}</p><p><MapPin /> {offer.regionLabel} · {quantity} 台 · {duration} {periodLabel(sku.period)}</p>{startsAtRaw && <p><CalendarBlank /> {new Date(startsAtRaw).toLocaleString('zh-CN')}</p>}</div></section><section className="compute-panel"><h2>联系信息</h2><div className="compute-form-grid"><label>联系人<input value={contactName} onChange={(event) => setContactName(event.target.value)} autoComplete="name" required /></label><label>联系电话<input value={contactPhone} onChange={(event) => setContactPhone(event.target.value)} inputMode="tel" autoComplete="tel" required /></label></div><p className="compute-field-help">仅用于本订单，不会反写统一账户。</p></section><label className="compute-consent"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} /><span>我已阅读并同意当前版本服务条款、退款规则和第三方责任边界；提交询价不代表库存已锁定或合同成立。</span></label></div><aside><PriceBreakdown subtotal={subtotal} quote={quote} />{submitError && <p className="compute-inline-error" role="alert">{submitError}</p>}<button type="button" className="compute-button primary" disabled={submitting} onClick={submit}>{submitting ? '正在提交…' : quote ? '确认提交租赁需求' : `确认支付 ${formatCardHours(subtotal)} 卡时`}</button></aside></div>;
}
