import { useState } from 'react';
import { ErrorState } from '../components/ErrorState';
import { StatusTimeline } from '../components/StatusTimeline';
import { useComputeResource } from '../hooks/useComputeResource';
import type { ComputePageProps } from './shared';

export function DeviceDetailPage({ api, deviceId }: ComputePageProps & { deviceId: string }) {
  const resource = useComputeResource((signal) => api.device(deviceId, signal), [deviceId]); const [showTicket, setShowTicket] = useState(false); const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [message, setMessage] = useState('');
  if (resource.state === 'error') return <ErrorState message={resource.error?.message} onRetry={resource.reload} />; if (!resource.data) return <div className="compute-skeleton detail-card" />; const device = resource.data;
  const submitTicket = async () => { try { await api.createTicket(device.id, { category: 'incident', subject, description }); setMessage('工单已创建。'); setShowTicket(false); } catch (error) { setMessage(error instanceof Error ? error.message : '创建失败'); } };
  return <div className="compute-detail-layout"><div className="compute-detail-primary"><section className="compute-panel"><span className={`compute-status-pill ${device.status}`}>{device.status}</span><h2>{device.name}</h2><dl className="compute-definition-grid"><div><dt>GPU</dt><dd>{device.gpuModel} · {device.gpuCount} 卡</dd></div><div><dt>区域</dt><dd>{device.regionLabel}</dd></div><div><dt>最近心跳</dt><dd>{device.lastHeartbeatAt ? new Date(device.lastHeartbeatAt).toLocaleString('zh-CN') : '专用监控尚未接入'}</dd></div><div><dt>近 24h 可用率</dt><dd>{device.availability24hPercent === null ? '监控未接入，已隐藏' : `${device.availability24hPercent}%`}</dd></div></dl>{device.actionRequired && <p className="compute-inline-error">待处理：{device.actionRequired}</p>}</section><section className="compute-panel"><h2>部署与状态时间线</h2><StatusTimeline events={device.events} /></section></div><aside className="compute-panel"><h2>运维操作</h2><button type="button" className="compute-button primary" onClick={() => setShowTicket(true)}>创建工单</button><button type="button" className="compute-button secondary" onClick={() => setShowTicket(true)}>申请维护 / 退场</button>{showTicket && <div className="compute-ticket-form"><label>工单主题<input value={subject} onChange={(event) => setSubject(event.target.value)} /></label><label>问题说明<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><button type="button" className="compute-button primary" onClick={submitTicket}>提交工单</button></div>}{message && <p role="status">{message}</p>}<p>温度、利用率和收益仅在真实 metrics 与结算系统接入后展示。</p></aside></div>;
}
