import type { HostingApplicationDraft } from '@cod/contracts/compute-market-v2';
import { Check, FloppyDisk } from '@phosphor-icons/react';
import { useEffect, useState } from 'react';
import type { ComputePageProps } from './shared';

const draftKey = 'cod.compute.hosting-draft.v2';
const emptyDraft: HostingApplicationDraft = { subjectType: 'individual', verificationStatus: 'unverified', contactName: '', contactPhone: '', city: '', devices: [{ brand: '', model: '', gpuModel: '', gpuCount: 1, gpuMemoryGb: null, deliveryMode: 'bare_metal', gpuInterconnectLabel: '', cpuModel: '', cpuCores: null, ramGb: null, systemDiskGb: null, dataDiskGb: null, operatingSystem: 'Ubuntu 22.04 LTS', driverVersion: '', cudaVersion: '', frameworks: ['PyTorch'], networkLabel: '', askingPriceCnyPerGpuHour: null, minimumRentalHours: null, serialLastFour: '', machineSpecs: '', ownershipProofStatus: 'pending' }], rackUnits: null, powerWatts: null, networkRequirement: '', hostingMonths: null, availableFrom: null, slaRequirement: '', settlementPreference: '', responsibilityAccepted: false, privacyAccepted: false };

const frameworkOptions = ['PyTorch', 'TensorFlow', 'vLLM', 'ComfyUI', 'JupyterLab', '纯净镜像'];
const deliveryLabels = { container: '容器实例', virtual_machine: '独占虚拟机', bare_metal: '裸金属整机' } as const;

export function HostingApplyPage({ api, navigate }: ComputePageProps) {
  const [step, setStep] = useState(1); const [draft, setDraft] = useState<HostingApplicationDraft>(() => { try { return JSON.parse(localStorage.getItem(draftKey) ?? '') as HostingApplicationDraft; } catch { return emptyDraft; } }); const [message, setMessage] = useState(''); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { try { localStorage.setItem(draftKey, JSON.stringify(draft)); } catch { /* storage is optional */ } }, [draft]);
  const device = draft.devices[0]; const patch = (next: Partial<HostingApplicationDraft>) => setDraft((current) => ({ ...current, ...next })); const patchDevice = (next: Partial<typeof device>) => patch({ devices: [{ ...device, ...next }] });
  const save = async () => { setSubmitting(true); setMessage(''); try { await api.createHostingApplication(draft, false); setMessage('草稿已安全保存。'); } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败'); } finally { setSubmitting(false); } };
  const submit = async () => { setSubmitting(true); setMessage(''); try { const application = await api.createHostingApplication(draft, true); try { localStorage.removeItem(draftKey); } catch { /* optional */ } navigate(`/compute/hosting/applications/${application.id}`); } catch (error) { setMessage(error instanceof Error ? error.message : '提交失败'); } finally { setSubmitting(false); } };
  return <div className="compute-form-page"><ol className="compute-step-header">{['主体联系', '设备清单', '机房需求', '确认提交'].map((label, index) => <li className={step >= index + 1 ? 'active' : ''} key={label}><span>{step > index + 1 ? <Check /> : index + 1}</span><strong>{label}</strong></li>)}</ol><section className="compute-panel compute-wizard">
    {step === 1 && <><h2>主体与联系方式</h2><div className="compute-form-grid"><label>主体类型<select value={draft.subjectType} onChange={(event) => patch({ subjectType: event.target.value as HostingApplicationDraft['subjectType'] })}><option value="individual">个人</option><option value="enterprise">企业</option></select></label><label>认证状态<select value={draft.verificationStatus} onChange={(event) => patch({ verificationStatus: event.target.value as HostingApplicationDraft['verificationStatus'] })}><option value="unverified">未认证</option><option value="pending">认证中</option><option value="verified">已认证</option></select></label><label>联系人<input value={draft.contactName} onChange={(event) => patch({ contactName: event.target.value })} /></label><label>联系电话<input inputMode="tel" value={draft.contactPhone} onChange={(event) => patch({ contactPhone: event.target.value })} /></label><label>所在城市<input value={draft.city} onChange={(event) => patch({ city: event.target.value })} /></label></div></>}
    {step === 2 && <><h2>设备与可售配置</h2><p className="compute-field-help">按实际可交付配置填写。公开参考价用于判断市场区间，不代表 COD 最终收购或租赁报价。</p><div className="compute-form-grid">
      <label>品牌<input value={device.brand} onChange={(event) => patchDevice({ brand: event.target.value })} /></label><label>整机型号<input value={device.model} onChange={(event) => patchDevice({ model: event.target.value })} /></label>
      <label>GPU 型号<input value={device.gpuModel} onChange={(event) => patchDevice({ gpuModel: event.target.value })} placeholder="例如 H100 SXM" /></label><label>GPU 数量<input type="number" min="1" max="64" value={device.gpuCount} onChange={(event) => patchDevice({ gpuCount: Number(event.target.value) })} /></label>
      <label>单卡显存（GB）<input type="number" min="1" value={device.gpuMemoryGb ?? ''} onChange={(event) => patchDevice({ gpuMemoryGb: Number(event.target.value) || null })} /></label><label>交付形态<select value={device.deliveryMode ?? 'bare_metal'} onChange={(event) => patchDevice({ deliveryMode: event.target.value as NonNullable<typeof device.deliveryMode> })}><option value="bare_metal">裸金属整机</option><option value="virtual_machine">独占虚拟机</option><option value="container">容器实例</option></select></label>
      <label>GPU 互联<input value={device.gpuInterconnectLabel ?? ''} onChange={(event) => patchDevice({ gpuInterconnectLabel: event.target.value })} placeholder="例如 NVLink / NVSwitch / PCIe" /></label><label>CPU 型号<input value={device.cpuModel ?? ''} onChange={(event) => patchDevice({ cpuModel: event.target.value })} placeholder="例如 AMD EPYC 9654" /></label>
      <label>CPU 核数<input type="number" min="1" value={device.cpuCores ?? ''} onChange={(event) => patchDevice({ cpuCores: Number(event.target.value) || null })} /></label><label>内存（GB）<input type="number" min="1" value={device.ramGb ?? ''} onChange={(event) => patchDevice({ ramGb: Number(event.target.value) || null })} /></label>
      <label>系统盘（GB）<input type="number" min="1" value={device.systemDiskGb ?? ''} onChange={(event) => patchDevice({ systemDiskGb: Number(event.target.value) || null })} /></label><label>数据盘（GB）<input type="number" min="0" value={device.dataDiskGb ?? ''} onChange={(event) => patchDevice({ dataDiskGb: Number(event.target.value) || null })} /></label>
      <label>操作系统<input value={device.operatingSystem ?? ''} onChange={(event) => patchDevice({ operatingSystem: event.target.value })} placeholder="例如 Ubuntu 22.04 LTS" /></label><label>NVIDIA 驱动<input value={device.driverVersion ?? ''} onChange={(event) => patchDevice({ driverVersion: event.target.value })} placeholder="例如 550.x" /></label>
      <label>CUDA 版本<input value={device.cudaVersion ?? ''} onChange={(event) => patchDevice({ cudaVersion: event.target.value })} placeholder="例如 CUDA 12.4" /></label><label>网络能力<input value={device.networkLabel ?? ''} onChange={(event) => patchDevice({ networkLabel: event.target.value })} placeholder="例如 10G 公网 / 100G IB" /></label>
      <fieldset className="compute-framework-field span-2"><legend>可交付软件环境</legend><div>{frameworkOptions.map((framework) => { const checked = device.frameworks?.includes(framework) ?? false; return <label key={framework}><input type="checkbox" checked={checked} onChange={() => patchDevice({ frameworks: checked ? (device.frameworks ?? []).filter((item) => item !== framework) : [...(device.frameworks ?? []), framework] })} /><span>{framework}</span></label>; })}</div></fieldset>
      <label>期望报价（元 / 卡 / 小时）<input type="number" min="0" step="0.01" value={device.askingPriceCnyPerGpuHour ?? ''} onChange={(event) => patchDevice({ askingPriceCnyPerGpuHour: Number(event.target.value) || null })} /></label><label>最低租用时长（小时）<input type="number" min="1" value={device.minimumRentalHours ?? ''} onChange={(event) => patchDevice({ minimumRentalHours: Number(event.target.value) || null })} /></label>
      <label>序列号后四位<input maxLength={4} value={device.serialLastFour} onChange={(event) => patchDevice({ serialLastFour: event.target.value.toUpperCase() })} /></label><label>产权证明状态<select value={device.ownershipProofStatus} onChange={(event) => patchDevice({ ownershipProofStatus: event.target.value as 'ready' | 'pending' })}><option value="pending">待准备</option><option value="ready">已准备</option></select></label>
      <label className="span-2">其他整机规格<textarea value={device.machineSpecs} onChange={(event) => patchDevice({ machineSpecs: event.target.value })} placeholder="可补充主板、机箱、电源、散热、机房和维护状态" /></label>
    </div></>}
    {step === 3 && <><h2>机房需求</h2><div className="compute-form-grid"><label>U 数<input type="number" min="1" value={draft.rackUnits ?? ''} onChange={(event) => patch({ rackUnits: Number(event.target.value) || null })} /></label><label>功耗（W）<input type="number" min="1" value={draft.powerWatts ?? ''} onChange={(event) => patch({ powerWatts: Number(event.target.value) || null })} /></label><label>托管周期（月）<input type="number" min="1" value={draft.hostingMonths ?? ''} onChange={(event) => patch({ hostingMonths: Number(event.target.value) || null })} /></label><label>可进场时间<input type="date" value={draft.availableFrom ?? ''} onChange={(event) => patch({ availableFrom: event.target.value })} /></label><label>网络需求<input value={draft.networkRequirement} onChange={(event) => patch({ networkRequirement: event.target.value })} /></label><label>运维 / SLA<input value={draft.slaRequirement} onChange={(event) => patch({ slaRequirement: event.target.value })} /></label><label className="span-2">结算偏好<input value={draft.settlementPreference} onChange={(event) => patch({ settlementPreference: event.target.value })} placeholder="仅作后续商务核验" /></label></div></>}
    {step === 4 && <><h2>确认提交</h2><dl className="compute-definition-grid"><div><dt>主体</dt><dd>{draft.subjectType === 'enterprise' ? '企业' : '个人'} · {draft.contactName || '未填写'}</dd></div><div><dt>设备</dt><dd>{device.gpuModel || '未填写'} · {device.gpuCount} 卡 · {device.gpuMemoryGb ?? '-'} GB</dd></div><div><dt>交付形态</dt><dd>{deliveryLabels[device.deliveryMode ?? 'bare_metal']}</dd></div><div><dt>软件环境</dt><dd>{device.frameworks?.length ? device.frameworks.join('、') : '未填写'}</dd></div><div><dt>运行环境</dt><dd>{device.operatingSystem || '未填写'} · {device.cudaVersion || 'CUDA 待确认'}</dd></div><div><dt>期望报价</dt><dd>{device.askingPriceCnyPerGpuHour ? `¥${device.askingPriceCnyPerGpuHour} / 卡 / 小时` : '待商务报价'}</dd></div><div><dt>机房需求</dt><dd>{draft.rackUnits ?? '-'} U · {draft.powerWatts ?? '-'} W · {draft.hostingMonths ?? '-'} 个月</dd></div><div><dt>所在城市</dt><dd>{draft.city || '未填写'}</dd></div></dl><label className="compute-consent"><input type="checkbox" checked={draft.responsibilityAccepted} onChange={(event) => patch({ responsibilityAccepted: event.target.checked })} /><span>我理解申请不代表 COD 已接收设备；正式责任以书面合同为准。</span></label><label className="compute-consent"><input type="checkbox" checked={draft.privacyAccepted} onChange={(event) => patch({ privacyAccepted: event.target.checked })} /><span>我同意按隐私说明处理联系人与设备资料。</span></label></>}
    {message && <p className="compute-inline-message" role="status">{message}</p>}<div className="compute-wizard-actions"><button type="button" className="compute-button secondary" disabled={submitting} onClick={save}><FloppyDisk /> 保存草稿</button>{step > 1 && <button type="button" className="compute-button secondary" onClick={() => setStep((value) => value - 1)}>上一步</button>}{step < 4 ? <button type="button" className="compute-button primary" onClick={() => setStep((value) => value + 1)}>下一步</button> : <button type="button" className="compute-button primary" disabled={submitting} onClick={submit}>{submitting ? '提交中…' : '确认提交'}</button>}</div>
  </section></div>;
}
